-- Migration number: 0004 	 2025-09-03T04:15:56.061Z

-- Add description column to goals table
ALTER TABLE goals ADD COLUMN description TEXT;

-- Update goals with descriptions from CSV data (first 30 entries)
UPDATE goals SET description = 'The story begins not in a king''s court or a fortress of old, but in the peaceful, sun-dappled hills of the Shire, within the very heart of the hobbit-hole known as Bag End. Here, amidst the quiet comfort of home, the fate of Middle-earth was sealed. It was upon the occasion of a long-expected party for Bilbo Baggins that a seemingly simple act transpired: the passing of a golden ring to his young heir, Frodo. Yet even in this moment of warmth and celebration, a strange shadow fell, for Bilbo''s words turned evasive and his spirit weary, hinting at the sinister power of the heirloom he now bequeathed. This tranquil setting, a sanctuary of innocence, would soon be left behind, its simple comforts serving as a precious memory for the long and perilous road ahead.' WHERE distance = 0 * 1.60934;

UPDATE goals SET description = 'The initial leg of Frodo''s quest began not with a grand march, but as a hurried and clandestine flight from the Shire to evade the relentless pursuit of the Black Riders. Frodo, Sam, and Pippin, their hearts filled with a mix of fear and resolve, traveled by night, leaving the warmth of their hobbit-holes behind. Their path wound through the familiar landscapes of their home, which now seemed alien and menacing under the threat of pursuit. They crossed a small plank bridge over the stream known as "The Water," a mundane act that became their first true step out of the Shire''s protective embrace and into a world of ever-present danger.' WHERE distance = 3 * 1.60934;

UPDATE goals SET description = 'Continuing their frantic journey, the hobbits crossed the Great Road, a wide path leading from the Brandywine Bridge. This crossing marked their entry into Tookland, a part of the Shire known for its adventurous inhabitants. The hobbits, however, were not in the mood for adventure. Every rustle in the hedgerows and every shadow that lengthened in the pale moonlight was a cause for alarm, for they knew the Black Riders were searching for them. This conscious choice to leave the main road was a desperate strategy to outwit their pursuers, moving them ever deeper into the uncertain wilderness of Middle-earth.' WHERE distance = 5 * 1.60934;

UPDATE goals SET description = 'Onward they pressed, a quiet and hurried procession, leaving the familiar paths behind in their desperate flight. As they reached Stock Road, a thread of worn earth leading ever eastward, the once-peaceful lanes of the Shire seemed to twist into a labyrinth of peril. Though still in their homeland, the air was thick with the threat of pursuit, and every landmark, including this road, was a matter of grave import. It was but another milestone in their race against an unseen evil, a desperate hope that they might pass the border of the Shire''s protected lands unnoticed.' WHERE distance = 15 * 1.60934;

UPDATE goals SET description = 'The hobbits'' journey was haunted by the constant, terrifying presence of the Black Riders, Sauron''s nine fearsome Ringwraiths, who relentlessly pursued the Ring-bearer. These cloaked figures on their black steeds were a tangible manifestation of evil, transforming the once-peaceful Shire into a place of mortal terror. The hobbits were forced to hide in hedgerows, to remain silent in the darkness, and to travel by night to evade detection and capture. Their constant, menacing presence underscored the immense stakes of the quest and the very real danger that followed them with every step.' WHERE distance = 32 * 1.60934;

UPDATE goals SET description = 'In a moment of unexpected grace, the hobbits stumbled upon a company of wandering Elves, led by the noble Gildor Inglorion. This meeting, which seemed a chance happening, was a moment of profound comfort and light in the growing darkness. The Elves, a race of ancient wisdom and beauty, offered the hobbits food, shelter, and companionship, their songs a beautiful reminder of a world beyond the growing shadow. They promised to send word ahead to friends, an act of kindness that foreshadowed the great alliance of races that would later form to oppose Sauron. This encounter was the first taste of aid from a non-hobbit race, and it left the hobbits with a fleeting glimpse of hope.' WHERE distance = 41 * 1.60934;

UPDATE goals SET description = 'Frodo, still holding a childhood fear of the stout hobbit farmer and his dogs, was terrified to approach Bamfurlong, a farm in the Marish. Yet this visit became a powerful moment of quiet heroism, for Farmer Maggot proved to be a steadfast bastion against evil. He recounted how a Black Rider had recently come to his farm asking about ''Baggins,'' but despite the sinister nature of the stranger, Maggot drove him away with a stout heart and his brave hounds. The farmer''s simple defiance and hospitality served as a microcosm of the larger struggle, demonstrating that courage and resistance are not confined to great warriors, but are found in the steadfastness of the common folk.' WHERE distance = 61 * 1.60934;

UPDATE goals SET description = 'The hobbits'' flight from the Shire culminated in a pivotal, symbolic moment at the Bucklebury Ferry. As the ferry-boat moved slowly across the Brandywine River, with the Black Riders appearing on the bank they had just left, the hobbits felt a sense of finality. Sam, in particular, had a strange feeling as the "slow gurgling stream slipped by: his old life lay behind in the mists, dark adventure lay in front." The crossing was a point of no return, signifying their definitive departure from the Shire''s protected borders and their full entry into the wider world, with the river now standing as a barrier between their safe past and their perilous future.' WHERE distance = 70 * 1.60934;

UPDATE goals SET description = 'After crossing the Brandywine, the hobbits found a brief refuge in the house at Crickhollow, a safe house in Buckland. This location, though still within the Shire''s lands, was on its very edge, a temporary sanctuary before they had to make a dangerous detour into the Old Forest to escape their relentless pursuers. It was a moment of calm before a storm, a final chance to rest before they were forced to confront new, more ancient evils. This short period of respite gave them a false sense of security, which would be shattered by the dangers that lay just beyond the garden gate.' WHERE distance = 73 * 1.60934;

UPDATE goals SET description = 'In a prolonged detour to evade the Black Riders, the hobbits entered the Old Forest, a place filled with malevolent and ancient trees. The woods seemed to have a will of their own, leading the hobbits astray and bewildering their sense of direction. They were forced up a knoll where the trees closed in around them, their branches seeming to press in, their roots like fingers reaching from the earth. This experience was a narrative trial, forcing the hobbits to confront a new and more ancient form of malevolence before they were saved by the enigmatic Tom Bombadil.' WHERE distance = 87 * 1.60934;

UPDATE goals SET description = 'Deep within the malevolent embrace of the Old Forest, the hobbits were trapped and attacked by the ancient, personified tree, Old Man Willow. Its roots ensnared Merry and Pippin, and its trunk threatened to swallow them whole. Frodo and Sam, in a moment of sheer terror, were helpless. It was only through the timely and inexplicable arrival of the mysterious Tom Bombadil that they were rescued from certain doom. This frightening encounter served to introduce a different, more ancient type of danger than the Black Riders, preparing the hobbits for the wider, more fantastical world of Middle-earth.' WHERE distance = 95 * 1.60934;

UPDATE goals SET description = 'After their harrowing rescue from Old Man Willow, the hobbits were taken to the house of the enigmatic Tom Bombadil and his wife, Goldberry. Their home was a sanctuary of profound peace and a place wholly immune to the Ring''s influence, which the hobbits discovered when the Ring had no effect on Bombadil himself. The hobbits rested here for two nights and a day, sharing songs and stories with the strange, jolly old man who existed outside the traditional power structures of Middle-earth. This unexpected refuge was a moment of pure "eucatastrophe," a miraculous grace that saved the heroes from certain doom and gave them a glimpse of a power that was neither for Sauron nor against him.' WHERE distance = 98 * 1.60934;

UPDATE goals SET description = 'After leaving the sanctuary of Tom Bombadil''s house, the hobbits journeyed across the Barrow-downs, a place shrouded in a heavy mist and a lingering sense of ancient evil. Here, they were captured by a terrifying, undead barrow-wight, who ensnared them in a dark mound and cast a spell upon them. It was Frodo''s cry for help, a desperate prayer to his strange new friend, that brought Tom Bombadil once more to their aid. He not only rescued them from the barrow-wight but gave them ancient blades, which would prove crucial later in their quest. This experience was a miniature of the larger epic, a trial that prepared them for the far greater eucatastrophes that would save them at the very end.' WHERE distance = 115 * 1.60934;

UPDATE goals SET description = 'Emerging from the peril of the Barrow-downs, the hobbits arrived at the village of Bree and its famous inn, The Prancing Pony. This unique location, a place where men and hobbits lived side by side, was a crucial "point of transition" that eased them from the familiarity of the Shire to the dangers of the wide world. It was here, in a moment of accidental clumsiness, that Frodo slipped on the Ring and vanished, an act that alerted Sauron''s spies to his presence. This incident precipitated the pivotal meeting with the Ranger known as Strider, a rough-looking but trustworthy man who would become their new guide.' WHERE distance = 135 * 1.60934;

UPDATE goals SET description = 'Under the new guidance of Strider, the hobbits left the relative safety of Bree and took a less-traveled route through the dense woods of Chetwood. This difficult path was chosen to evade the relentless pursuit of the Black Riders and Saruman''s spies. This section of the journey was a grueling "forced march" that contrasted starkly with their earlier, more leisurely travels, highlighting the sheer urgency and danger of their quest. Camping in these dark woods, they found a temporary, but tense, respite before continuing their long and arduous trek toward the ominous hill of Weathertop.' WHERE distance = 147 * 1.60934;

UPDATE goals SET description = 'After a tense night of camping, the hobbits and Aragorn left the Chetwood, continuing their difficult march through the wild lands of Eriador. Their path was rugged and untrodden, a desperate race against the clock and the relentless Nazgûl. The constant movement, with little rest, was a testament to the immense peril they were in, and a grim reminder of their decision to leave the safety of the main roads. They pressed onward, guided by the steadfast Ranger, toward the ominous Weather Hills that rose in the distance.' WHERE distance = 165 * 1.60934;

UPDATE goals SET description = 'The hobbits and Aragorn found a brief, anxious respite as they made camp in the Western Marshes. This part of their journey was characterized by a grueling, forced march to evade the Black Riders before they reached the Weather Hills. The desolate and dangerous landscape, filled with treacherous pools and hidden dangers, reflected the increasing peril of their mission. Their camp was a place of deep unease and brief, restless slumber, as the constant threat of pursuit hung over them and they were unable to find true rest.' WHERE distance = 179 * 1.60934;

UPDATE goals SET description = 'The hobbits and Aragorn reached the eastern edge of the Midgewater Marshes, a place known for its treacherous terrain and unpleasant insects. The landscape was becoming increasingly wild and inhospitable, a stark contrast to the comfortable Shire they had left behind. This location, with its dense fens and buzzing swarms of insects, was just one of many small obstacles they had to overcome on their winding, difficult route to Rivendell, and it served to highlight the sheer difficulty of their journey.' WHERE distance = 198 * 1.60934;

UPDATE goals SET description = 'As night fell, the hobbits made camp by a small stream among stunted alder trees. This mundane act of setting up camp in the wild was a constant feature of their journey. Under the watchful guidance of Aragorn, they had to find hidden spots to rest, always with a sense of unease. This location provided a brief, tense moment of respite as they continued their arduous flight from the Black Riders, with the ominous Weather Hills looming ahead of them in the distance like a grim promise.' WHERE distance = 211 * 1.60934;

UPDATE goals SET description = 'The hobbits and Aragorn made their final camp at the foot of the Weather Hills, a crucial stop before their fateful encounter with the Nazgûl. From this location, they could see the ominous hill of Weathertop rising in the distance, a place where a great watchtower once stood. Their anxiety was heightened by this visible landmark, for they knew the Ringwraiths were likely to be searching the area. This camp was the last moment of relative peace before a major, climactic event that would irrevocably change the course of their quest and test their courage to its very limit.' WHERE distance = 229 * 1.60934;

UPDATE goals SET description = 'Upon the desolate summit of Weathertop, the ancient hill of Amon Sûl, the hobbits were ambushed by five Nazgûl, led by the Witch-king. In the ensuing struggle, a terrible wound was inflicted upon Frodo by a Morgul-blade, a dark weapon that began a slow process of his transformation into a wraith. The attack on this ancient watchtower was a major turning point, forcing the group into a desperate, twenty-seven-day flight as Frodo''s health waned. His wound was a constant reminder of the immense peril of their mission and the ever-present threat of their foes.' WHERE distance = 241 * 1.60934;

UPDATE goals SET description = 'The party, now a desperate band of weary travelers, made camp in thickets south of the Great East Road. This was part of a frantic, twenty-seven-day forced march as Frodo''s health continued to wane from the Morgul-blade wound. They had to travel quickly and secretly, avoiding main roads and any sign of pursuit. Each night was spent in a new, hidden location, with little rest, as the constant threat of the Nazgûl and Frodo''s deteriorating condition drove them onward, their hope fading with each passing hour.' WHERE distance = 260 * 1.60934;

UPDATE goals SET description = 'The party stopped to make a tense, temporary camp during their desperate, forced march toward Rivendell. Frodo''s health continued to deteriorate from the Morgul-blade wound, and his companions had to do everything they could to keep him moving. Each night they found a small, temporary refuge in the wilderness, but the threat of the Nazgûl remained a constant, unseen force. This period of the journey was defined by its relentlessness, a grim trial with little in the way of rest or comfort.' WHERE distance = 271 * 1.60934;

UPDATE goals SET description = 'The desperate group continued their flight, following a wide, shallow, curving valley as they raced toward the final threshold of safety. The Nazgûl were in close pursuit, and Frodo''s wound took a continuous, agonizing toll on him with every step. The landscape itself seemed to contribute to the grim mood of the journey, with every turn of the valley presenting another uncertainty. They had to travel as quickly as possible to reach the Last Bridge and the protection that lay just beyond it, a desperate gamble against fate.' WHERE distance = 298 * 1.60934;

UPDATE goals SET description = 'The party continued its desperate journey to Rivendell through the valley. They were pursued by the Nazgûl and had to stay hidden and travel quickly, as Frodo''s condition worsened with every passing moment. The valley provided some cover from the ever-present threat of the Nazgûl, but they were still on high alert, knowing that they were not safe until they reached the Ford of Bruinen. The constant motion and the mounting anxiety of the hobbits were a central theme of this part of the journey.' WHERE distance = 328 * 1.60934;

UPDATE goals SET description = 'The hobbits and their guide, Aragorn, safely crossed the Last Bridge over the Hoarwell River. This was a significant landmark on their journey, marking their passage from the Lone-lands into a region closer to Rivendell. Aragorn was anxious, fearing that the Nazgûl would have already arrived there before them. But they passed safely and kept moving toward their destination. This crossing provided a brief moment of relief and a renewed sense of hope that they would reach the safety of Rivendell in time, a small victory in a journey of immense peril.' WHERE distance = 358 * 1.60934;

UPDATE goals SET description = 'As they continued on the road to Rivendell, the hobbits encountered the stone trolls from Bilbo''s past adventure, a familiar sight on the path. The sight of these petrified creatures, a physical manifestation of a tale they had only heard, signaled that they were nearing their destination, a place where Bilbo once found rest and healing. It was a tangible link to a past adventure, one that was far less perilous than the one they were on. For the hobbits, their presence was a powerful sign that they were nearing the sanctuary of Rivendell.' WHERE distance = 392 * 1.60934;

UPDATE goals SET description = 'Frodo''s life was waning as the poison from the Morgul-blade began to take full effect. He was on the verge of turning into a wraith when he met the Elf-lord Glorfindel. This powerful ally, a being of ancient grace, arrived just in time to provide assistance. He placed the fading Frodo on his horse and raced him toward the Ford of Bruinen to evade the pursuing Nazgûl. This miraculous arrival was an essential act of grace and a clear example of "eucatastrophe," a sudden, joyous salvation that saved Frodo from a grim fate and enabled him to reach the sanctuary of Rivendell for healing.' WHERE distance = 405 * 1.60934;

UPDATE goals SET description = 'The desperate chase culminated at the Ford of Bruinen, a river that served as the final natural defense of Rivendell. As the Nazgûl cornered Frodo, a magical, providential flood, conjured by Elrond, swept away the Black Riders and their steeds. The flood, resembling a stampede of horses, engulfed the Nazgûl and saved Frodo from certain doom. He fainted upon reaching the other side, having been saved just in time from becoming a wraith. This climactic event marked the end of Frodo''s flight and the beginning of his recovery.' WHERE distance = 450 * 1.60934;

UPDATE goals SET description = 'The hobbits finally reached the hidden Elven sanctuary of Rivendell, also known as Imladris, where Frodo was healed by the Elf-lord Elrond. This was not a place of action, but a haven of refuge and restoration, where Frodo and his companions could recover from their harrowing journey. It was here that the wisdom of the world was gathered at the Council of Elrond to decide the Ring''s fate. The sanctuary served as a cultural stronghold, preserving ancient lore and providing the hobbits with the necessary supplies and knowledge to continue their quest, including Bilbo''s sword Sting and a mithril shirt.' WHERE distance = 458 * 1.60934;

-- Next 30 entries (31-60)
UPDATE goals SET description = 'On the morning of December 25th, a poignant and symbolic date, the newly formed Fellowship of the Ring departed from the sanctuary of Rivendell. They crossed the Ford of Bruinen, the same river that had saved Frodo weeks earlier, and began their new, urgent quest to destroy the One Ring. Leaving the sanctuary behind, they stepped once more into the wild, on a path that was long and perilous, taking them into the heart of Middle-earth on a journey from which there could be no return.' WHERE distance = 466 * 1.60934;

UPDATE goals SET description = 'After leaving the sanctuary of Rivendell, the Fellowship walked through a steep-sided canyon, a testament to the difficult terrain that lay ahead. The land, once filled with the warmth and light of the Elven realm, was becoming increasingly foreboding. Their path was harried by spies of the Enemy, including crows and hawks, who flew overhead, watching their every move. The Fellowship had to remain cautious, knowing they were constantly being watched as they made their way toward the mountain pass.' WHERE distance = 480 * 1.60934;

UPDATE goals SET description = 'The Fellowship crossed a small stream as they proceeded south from Rivendell. This small, mundane act of travel was a testament to the long and arduous journey that lay ahead. With the Misty Mountains looming ahead, they had to continue to move forward, crossing small obstacles on their path, as they made their way toward a fateful decision point that would take them into the heart of the mountains. Every step was a struggle, a difficult progression toward an uncertain future.' WHERE distance = 484 * 1.60934;

UPDATE goals SET description = 'The Fellowship reached the top of a small hill, where they could see snow-capped peaks to the east. This view of the towering Misty Mountains, including the peaks of Silvertine and Redhorn, was a powerful and ominous sign of the challenges to come. The sight of the mountains and the Pass of Caradhras reminded them of the looming peril of their quest and the difficulties that lay ahead. The landscape itself was a character, shaping their journey and forcing them to make difficult choices.' WHERE distance = 504 * 1.60934;

UPDATE goals SET description = 'The Fellowship reached and followed a small stream westward, a minor detour on their arduous journey south toward the Misty Mountains. This part of the journey was filled with small, unrecorded events of travel that highlighted the sheer scale of the epic quest. They were constantly navigating the natural landscape, following the lay of the land to reach their final destination, with the looming threat of Saruman''s spies and the watchful Eye of Sauron following them.' WHERE distance = 516 * 1.60934;

UPDATE goals SET description = 'The Fellowship reached the top of a rise and began to head southeast, making their way toward the Pass of Caradhras. This part of the journey was a grueling march, as they were constantly on the move. They were being watched from above by spies and had to remain vigilant to avoid detection. The change in direction signaled their imminent arrival at the mountains and the first major obstacle they would face after leaving Rivendell, a grim reminder of the difficult path they had chosen.' WHERE distance = 528 * 1.60934;

UPDATE goals SET description = 'The Fellowship reached another low mountain spur and began to descend in a southwest direction, nearing the Pass of Caradhras. This part of the journey was marked by the relentless, difficult terrain that tested their resolve. The continuous movement, with little rest, was a testament to the immense peril they were in. The landscape itself was a challenge, forcing them to adapt and press onward despite the mounting difficulties of the journey, with every step a struggle against the elements.' WHERE distance = 544 * 1.60934;

UPDATE goals SET description = 'The path the Fellowship was following came to a steep drop-off, forcing them to travel along a treacherous cliff top on their way to the Pass of Caradhras. This treacherous route highlighted the immense dangers they faced. They had to rely on their skill and bravery to navigate this difficult terrain, with the constant threat of a misstep or attack. This harrowing moment was just one of many that would test their courage on the path to the mountain pass.' WHERE distance = 548 * 1.60934;

UPDATE goals SET description = 'The Fellowship crossed a small stream as they continued their approach to the Misty Mountains. These small, mundane details of travel added to the realism of the journey. Every river and stream they crossed was another step closer to their destination, but it also presented a potential obstacle in their path, as they were on high alert for spies and any sign of danger, with the ominous mountains looming ahead.' WHERE distance = 560 * 1.60934;

UPDATE goals SET description = 'The Fellowship crossed a stream which flowed west to a swampy area, a minor obstacle on their southward journey. As they continued on their way, the terrain was becoming more difficult, a sign that they were nearing the mountains. They had to traverse these difficult lands to avoid the more heavily traveled paths, a necessary precaution to evade the watchful eye of the Enemy.' WHERE distance = 588 * 1.60934;

UPDATE goals SET description = 'The Fellowship reached a hilltop and turned southeast, continuing their path toward the Pass of Caradhras in the Misty Mountains. The change in direction signaled their imminent arrival at the mountains and the first major obstacle they would face after leaving Rivendell. The landscape itself was a character, with every hilltop and turn in the road forcing them to adapt and press onward despite the mounting difficulties of the journey.' WHERE distance = 608 * 1.60934;

UPDATE goals SET description = 'The Fellowship crossed a small stream, continuing their progress through the wild lands toward the Misty Mountains. These small, unrecorded events of travel were a testament to the sheer scale of the epic quest. They were constantly navigating the natural landscape, following the lay of the land to reach their final destination, with the looming threat of Saruman''s spies and the watchful Eye of Sauron following them.' WHERE distance = 627 * 1.60934;

UPDATE goals SET description = 'The Fellowship traversed rolling lands as they neared the Misty Mountains and their decision point at the Pass of Caradhras. The landscape was a welcome change from the more treacherous terrain they had been navigating, but the sense of unease remained. They were constantly aware of the presence of the Enemy, with spies flying overhead. The journey was a race against time, with every step bringing them closer to a final confrontation.' WHERE distance = 638 * 1.60934;

UPDATE goals SET description = 'The land dropped more steeply, and the Fellowship went southeast into a valley as they prepared to attempt the mountain pass. The terrain was a clear indicator that they were nearing the mountains. The valley provided some cover from the ever-present threat of the Nazgûl, but they were still on high alert. The constant motion and the mounting anxiety of the hobbits were a central theme of this part of the journey.' WHERE distance = 668 * 1.60934;

UPDATE goals SET description = 'The Fellowship crossed a final small stream before beginning their climb up toward the Pass of Caradhras. This mundane act of setting up camp in the wild was a constant feature of their journey. Under the watchful guidance of Aragorn, they had to find hidden spots to rest, always with a sense of unease. This location provided a brief, tense moment of respite as they prepared for the immense challenge that lay ahead.' WHERE distance = 675 * 1.60934;

UPDATE goals SET description = 'The Fellowship began their ascent up the northern side of Hollin Ridge, nearing the border of the region of Eregion, a landmark on their path to the mountains. This part of the journey was a difficult, uphill climb that tested their physical endurance. It was a sign that they were leaving the more gentle lands behind and entering a more treacherous and foreboding landscape, a place of immense peril and a grim reminder of the difficult path they had chosen.' WHERE distance = 686 * 1.60934;

UPDATE goals SET description = 'At the top of Hollin Ridge, the Fellowship was nearing the border of Eregion. As they stood on the summit, they were spied upon by a flock of Saruman''s spies, the Crebain. The sight of these black crows was an ominous sign that their movements had not gone unnoticed. It was a stark reminder of the immense power of their foes and the constant, unseen threats that followed them. The presence of the spies was a clear indicator that their attempts to travel secretly had failed, and they must now be even more cautious.' WHERE distance = 690 * 1.60934;

UPDATE goals SET description = 'Before the dawn, a time of deep darkness, the Fellowship sensed something flying overhead. It was a sign that they were still being watched by Saruman''s spies. The constant threat of being watched and discovered was a source of immense anxiety for the company. As they crossed a small stream, the seemingly mundane act was imbued with a sense of urgency and danger, as they knew they must continue to move quickly and secretly to evade their pursuers.' WHERE distance = 708 * 1.60934;

UPDATE goals SET description = 'The road climbed higher and higher as the Fellowship got closer to the foot of the Redhorn and the Pass of Caradhras. The landscape was becoming increasingly mountainous and difficult to traverse, a sign that they were nearing a major turning point in their journey. The relentless uphill climb tested their physical and mental endurance, as they were now fully committed to the arduous journey that lay ahead, with the promise of immense peril at the top.' WHERE distance = 733 * 1.60934;

UPDATE goals SET description = 'Almost at the foot of the Redhorn Pass, Gandalf and Aragorn, the two leaders of the company, debated their path. The air was turning colder, and they feared that heavy snow and rock slides would block their passage. Fearing the worst, the Fellowship collected wood in case they were forced to make camp in the mountains. This moment of debate and preparation highlighted the uncertainty of their quest and the immense dangers that lay ahead. It was a practical, mundane act that was imbued with a sense of foreboding, as they were now fully at the mercy of the elements.' WHERE distance = 742 * 1.60934;

UPDATE goals SET description = 'The Fellowship attempted to cross the Misty Mountains via the Pass of Caradhras, but they were stopped by heavy snow and rock slides. This failure was a crucial test of the Fellowship''s unity and resolve, and it compelled them to consider other routes. The mountains themselves seemed to be under a malevolent influence, resisting their passage with a will of their own. This failure forced them to make a perilous decision to take a shortcut through the ancient underground realm of the Dwarves: the Mines of Moria, a dark and dreadful place.' WHERE distance = 750 * 1.60934;

UPDATE goals SET description = 'The Fellowship, having been defeated by the mountain, descended from the pass and turned west, away from the path. They were now committed to a new, more dangerous route: through the Mines of Moria. As they descended, they were again harassed by Saruman''s spy-crows, the Crebain. The spies were a constant, menacing presence, reminding them that they were being watched and that their every move was known to the Enemy. This event underscored the immense peril of their journey and the lack of a truly safe path.' WHERE distance = 754 * 1.60934;

UPDATE goals SET description = 'As the Fellowship made its way to Moria, they were attacked by a savage pack of demonic were-wolves known as Wargs. The attack was a brutal, deadly battle in the wilderness that further tested the resolve of the Fellowship. The fight served to increase the sense of urgency and danger of their journey and cemented their decision to take the perilous shortcut through the Mines of Moria. The attack forced them to move forward, as they now knew they were being actively pursued by forces of the Enemy.' WHERE distance = 778 * 1.60934;

UPDATE goals SET description = 'The Fellowship reached the West-gate of the Mines of Moria, also known as the Gates of Khazad-dûm. As they attempted to enter, a monstrous creature known as the Watcher in the Water attacked them from the dark, cold lake. The assault forced them to retreat into the dark mines, and the way back was now sealed by the Watcher''s tentacles. With no choice but to push forward, they began their perilous journey through the vast, subterranean labyrinth of the Dwarves, a desolate and dreadful realm occupied by Orcs and a Balrog.' WHERE distance = 798 * 1.60934;

UPDATE goals SET description = 'Deep within the vast, subterranean complex of Moria, the Fellowship reached a junction of three passages with a guardroom. The sheer scale and complexity of the mines were overwhelming, and the company had to rely on Gandalf''s knowledge to navigate the dark, treacherous labyrinth. The ominous atmosphere of the ruined city and the fear of the unknown tested their courage with every step. The journey through this ruined city was a literal descent into a place saturated with forgotten evil.' WHERE distance = 818 * 1.60934;

UPDATE goals SET description = 'The Fellowship discovered the tomb of Balin, a dwarf-king who had attempted to re-colonize Moria, in the Chamber of Mazarbul. The discovery was a somber moment, a testament to the failed attempt to reclaim the ancient city. The moment of mourning was cut short when they were attacked by Orcs and a Troll. The valiant defense against this attack enabled the Fellowship to escape through another door, but it was a harrowing experience that led them to the climactic confrontation on Durin''s Bridge.' WHERE distance = 838 * 1.60934;

UPDATE goals SET description = 'After the climactic confrontation on Durin''s Bridge, where Gandalf sacrificed himself to allow the others to escape from the pursuing Balrog, the remaining Fellowship members fled from the Mines of Moria. They escaped through the Eastern Gates and reached the spring of the Silverlode, a place of light and running water. The loss of their leader shattered the Fellowship, forcing the remaining members to continue the quest without Gandalf. The exit from the dark mines to the light of the outside world was a poignant, emotional moment.' WHERE distance = 842 * 1.60934;

UPDATE goals SET description = 'After their harrowing escape from Moria, the remaining Fellowship members found a brief respite in the golden forests of Lothlórien. This Elven sanctuary, a land of light and healing ruled by the Lady Galadriel, was a thematic counterpart to the darkness of Moria. The Fellowship was welcomed into this land, where they found a temporary refuge from the perils of the wider world. It was a place of peace and beauty that provided them with a chance to rest and recover from the trauma of the mines and the loss of Gandalf.' WHERE distance = 855 * 1.60934;

UPDATE goals SET description = 'The Fellowship crossed the Silverlode river, a task made difficult by the Elves of Lothlórien, who provided a single line of rope for them to balance on. This precarious method of crossing was a test of their trust and skill. While in Lothlórien, the Fellowship was tested by the Lady Galadriel and given counsel and gifts, which would prove invaluable later on. The crossing was a small but memorable moment that demonstrated the unique nature of their time in the Elven-realm and their reliance on the Elves'' strange customs.' WHERE distance = 861 * 1.60934;

-- Next 30 entries (61-90)
UPDATE goals SET description = 'The Fellowship arrived at the hill of Cerin Amroth, a beautiful, sacred place within Lothlórien that offered a moment of light and healing. The hill was a place of profound significance, a symbol of the enduring beauty and power of the Elves. It was a moment of peace and reflection, and it provided a stark contrast to the darkness and despair of Moria. The arrival at this sacred place was a temporary respite that provided the Fellowship with a chance to recover from their harrowing journey.' WHERE distance = 906 * 1.60934;

UPDATE goals SET description = 'The Fellowship reached Caras Galadhon, the heart of Lothlórien, and met the Lady Galadriel and Lord Celeborn. Galadriel tested each member of the company, and her counsel and gifts would prove invaluable. She gave Frodo the Phial of Galadriel, a small but potent light that would be essential for his survival in the darkness to come. The meeting with these powerful Elves was a central event in the narrative, a moment of profound significance that provided the Fellowship with the tools and spiritual strength they would need to continue their quest.' WHERE distance = 920 * 1.60934;

UPDATE goals SET description = 'The Fellowship, having been rested and renewed, left the golden forests of Lothlórien. As they departed, Celeborn and Galadriel gave them boats and gifts for their journey down the Great River Anduin. This departure marked the end of their time of rest and healing. The gifts, including the Phial of Galadriel for Frodo and Elven cloaks for all, were a tangible sign of the Elves'' support and hope for the quest''s success. As they set off in their boats, they left the sanctuary of the Elven-realm behind, ready to face the new challenges that awaited them on the river.' WHERE distance = 930 * 1.60934;

UPDATE goals SET description = 'The Fellowship traveled by boat down the Great River Anduin, a long, winding waterway that led south toward their final destination. They made their first camp in the woods on the west bank of the river. This leg of the journey was marked by a sense of foreboding, as they were now in the heart of the wild lands, far from the protected realms of the Elves. They had to be vigilant, as the river was a major thoroughfare and they were not alone on it.' WHERE distance = 951 * 1.60934;

UPDATE goals SET description = 'The Fellowship camped again on the west bank of the Anduin, continuing their southward progress on the river. The journey was a long and arduous one, and the constant need to stop and rest highlighted the slow, difficult nature of their quest. Each night, they had to find a hidden place to make camp, as they were now in the heart of the wild lands. The constant movement, with little rest, was a testament to the immense peril they were in.' WHERE distance = 987 * 1.60934;

UPDATE goals SET description = 'As the Fellowship continued its journey down the Great River Anduin, the trees on the west bank began to thin out, and the sky became grey and overcast. The landscape was changing, a sign that they were nearing the end of their river journey and the more desolate lands that lay ahead. The oppressive atmosphere of the grey, overcast sky was a stark contrast to the golden, sun-dappled beauty of Lothlórien and a sign of the darkening world they were entering.' WHERE distance = 1008 * 1.60934;

UPDATE goals SET description = 'The Fellowship camped on flats north of the Field of Celebrant, a location of a past battle. The land was becoming more open and exposed, a sign that they were nearing a major turning point in their journey. The location, with its history of past conflict, served as a foreboding reminder of the immense battles that had been fought in Middle-earth. Their camp here was a temporary refuge before they must face a new, more immediate danger.' WHERE distance = 1023 * 1.60934;

UPDATE goals SET description = 'The river broadened, and the sky remained grey and overcast as the Fellowship continued its voyage toward Amon Hen and the Falls of Rauros. The broadening of the river was a sign that they were nearing a major geographical feature and the end of their river journey. The oppressive, grey sky added to the sense of foreboding, as they were now fully committed to the dangerous journey that lay ahead.' WHERE distance = 1040 * 1.60934;

UPDATE goals SET description = 'The Fellowship reached the North Undeep, with stony beaches and gravel shoals, where they had to proceed carefully to avoid grounding their boats. This was a difficult, technical part of their journey that required them to be vigilant and skilled. The treacherous river and its shoals were a sign that they were nearing a major change in the landscape. The need for careful navigation was a metaphor for the difficult choices that lay ahead.' WHERE distance = 1063 * 1.60934;

UPDATE goals SET description = 'The River Limlight entered the Great River on the west, a geographical landmark on the Fellowship''s journey toward their ultimate split. This was a sign that they were now in the realm of Rohan and were nearing their final destination on the river. The confluence of the two rivers was a moment of decision, as they must soon choose which path to take. The river and its tributaries were a central feature of the landscape and a guide on their long journey.' WHERE distance = 1070 * 1.60934;

UPDATE goals SET description = 'As they traveled down the river, Sam''s keen eyes spotted a strange and unsettling sight: a small, dark creature following them on a log. It was Gollum, who had been following the Fellowship from the Mines of Moria. This was the first time the company was aware of the creature''s relentless pursuit, and it was a moment of great significance. The sight of the creature confirmed their worst fears: they were being followed, and a new threat had emerged from the shadows to dog their every step.' WHERE distance = 1075 * 1.60934;

UPDATE goals SET description = 'The Fellowship made camp on a small island, or eyot, near the western shore. It was here that Frodo and Sam secretly watched Gollum, now confirmed to be following them. Aragorn also kept a careful watch on the creature, realizing it was a new threat. The camp was a place of anxiety and tense anticipation, as they now knew they were being followed. The decision to make camp here was a direct result of their new awareness of the creature''s presence.' WHERE distance = 1083 * 1.60934;

UPDATE goals SET description = 'The Fellowship reached the north edge of the eastern South Undeep as they continued down the river. The river was becoming more difficult to navigate, and the shoals and rapids were a sign of the treacherous terrain that lay ahead. They had to navigate this difficult part of the river carefully, as they were now nearing the Falls of Rauros and the end of their river journey. The journey was a constant test of their skill and resolve.' WHERE distance = 1122 * 1.60934;

UPDATE goals SET description = 'The Fellowship reached the north edge of the western South Undeep, navigating the treacherous river on their voyage. The river was becoming more difficult to navigate, and the shoals and rapids were a sign of the treacherous terrain that lay ahead. The journey was a constant test of their skill and resolve, as they were now nearing the Falls of Rauros and the end of their river journey.' WHERE distance = 1142 * 1.60934;

UPDATE goals SET description = 'The Fellowship camped during the day with downs on both sides of the river, as they rested before the rapids. This was an unusual stop, but the need to rest and prepare for the difficult passage ahead was paramount. The downs provided a temporary, but exposed, refuge before they must face the dangerous Falls of Rauros. The camp was a moment of brief, anxious slumber, as they were now fully committed to the arduous journey that lay ahead.' WHERE distance = 1155 * 1.60934;

UPDATE goals SET description = 'The Fellowship reached the lowlands between the downs and the Emyn Muil, nearing the end of their river journey. The landscape was changing, a sign that they were nearing a major geographical feature and the end of their river journey. The Emyn Muil were a foreshadowing of the difficult, barren landscape Frodo and Sam would have to navigate after the Fellowship broke. This location was a sign that they were nearing a major turning point in their quest.' WHERE distance = 1180 * 1.60934;

UPDATE goals SET description = 'The Fellowship camped again during the day as they prepared to reach the Falls of Rauros and the breaking of the company. The camp was a moment of brief, anxious slumber, as they were now fully committed to the arduous journey that lay ahead. This was a final, fleeting moment of unity before the group was irrevocably broken and sent on different paths.' WHERE distance = 1205 * 1.60934;

UPDATE goals SET description = 'As the river journey drew to a close, hills appeared on the west, and the river passed through crumbling cliffs and chimneys. The landscape was becoming more difficult and foreboding, a sign that they were nearing a major turning point in their quest. The cliffs and chimneys were a metaphor for the difficulties that lay ahead, and the weathered stone was a sign of the long, dark history of Middle-earth.' WHERE distance = 1220 * 1.60934;

UPDATE goals SET description = 'The Fellowship reached the higher Emyn Muil, a desolate, rocky landscape of barren hills where Frodo and Sam would soon be left alone. This was a difficult, treacherous landscape that was a clear sign that they were nearing the Falls of Rauros and the end of their river journey. The ominous landscape was a foreshadowing of the immense hardships that lay ahead for the hobbits, a difficult journey that would test their resolve and their friendship.' WHERE distance = 1234 * 1.60934;

UPDATE goals SET description = 'The Fellowship made their final camp on the west shore of the river. They saw many birds circling during the day, and late in the afternoon, Legolas, with his keen Elven sight, spotted an eagle, a majestic sign of hope. They waited until full dark to leave, as they did not want to be seen. The sight of the eagle was a moment of hope, a sign that they were not alone and that there were forces of good in the world. They had to travel slowly and carefully, for their fate was soon to be decided.' WHERE distance = 1255 * 1.60934;

UPDATE goals SET description = 'At midnight, a time of deep darkness, Sam heard the racing water of the rapids of Sarn Gebir. Suddenly, an Orc attack forced the group to move upstream to a shallow bay. Legolas shot a Nazgûl''s flying beast, a powerful sign of the intense peril they were in. The Orc attack was a key event that happened on the river journey and was a well-known detail. The attack forced them to huddle in their boats and wait for the danger to pass, a harrowing ordeal before the breaking of the company.' WHERE distance = 1267 * 1.60934;

UPDATE goals SET description = 'In the fog of the next morning, the Fellowship had to carry their boats around the rapids and then camp by a pool. It was a grueling, physical task that tested their strength and resolve. They had to make two trips to carry their boats and packs to the foot of the rapids, a sign of the immense physical burden of their journey. The camp by the pool was a moment of brief, anxious slumber before a major turning point. The physical hardship of this passage was a key part of the narrative, a grim foreshadowing of the struggles to come.' WHERE distance = 1269 * 1.60934;

UPDATE goals SET description = 'The Fellowship passed between the great stone statues of the Argonath, an ancient monument of two kings. These towering figures, carved in the likeness of Isildur and Anárion, were a powerful symbol of the ancient strength and glory of the kingdom of Gondor. The passage through the Argonath was a moment of profound significance, a visual representation of their journey from the wild lands to the borders of the great kingdom. The statues were a landmark that marked a new stage in their quest, one that would soon come to a dramatic and painful end.' WHERE distance = 1288 * 1.60934;

UPDATE goals SET description = 'The Fellowship passed out of the chasm and into Nen Hithoel, a great lake, where they would soon make a fateful choice. The lake was a peaceful but foreboding location, a temporary refuge before the final, climactic event that would break the company. The lake was a place of reflection and decision, where the Fellowship had to decide whether to head toward Mordor on the east or toward the safety of the city of Minas Tirith to the west.' WHERE distance = 1290 * 1.60934;

UPDATE goals SET description = 'The Fellowship reached the lawn of Parth Galen below the hill of Amon Hen, the exact location of the breaking of the company. It was here that Boromir, overcome by the Ring''s corrupting influence, attempted to take it from Frodo. This act of betrayal led to a fight with Orcs, in which Boromir was killed and Merry and Pippin were captured. Frodo, seeing the danger the Ring posed to his friends, made the selfless decision to continue the quest alone, a moment that irrevocably split the narrative and marked a major turning point in the fate of Middle-earth.' WHERE distance = 1309 * 1.60934;

UPDATE goals SET description = 'Frodo and Sam, now alone, found themselves on the east of the river. The landscape of the Wetwang curved south as they began their lonely journey to Mordor with Gollum in pursuit. This barren, desolate land reflected their despair and the immense, lonely task ahead. Their struggle to navigate the desolate landscape mirrored their psychological burden, as they were now on their own, far from the support of their friends. The landscape itself was a character, a symbol of their isolated journey.' WHERE distance = 1341 * 1.60934;

UPDATE goals SET description = 'After days of being lost in the rocky, barren hills of Emyn Muil, Frodo and Sam captured the creature known as Gollum, who had been following them from Moria. This moment presented Frodo with a crucial moral dilemma. Sam, driven by mistrust, wanted to kill or abandon Gollum, but Frodo, showing a profound and surprising mercy, refused to harm him. He made Gollum swear an oath to guide them to Mordor, an oath taken on the Ring itself. This decision to show mercy was a non-heroic act that held monumental significance, for it planted the seed of the quest''s ultimate success.' WHERE distance = 1383 * 1.60934;

UPDATE goals SET description = 'Guided by Gollum, Frodo and Sam entered the foul-smelling Dead Marshes, a treacherous swamp filled with the ghostly faces of slain warriors from a long-ago battle. This passage was a descent into a landscape that had been literally corrupted by past violence, a physical manifestation of evil''s lasting power. The oppressive atmosphere, constant stench, and the terrifying threat of the Nazgûl flying overhead tested the hobbits'' resolve and highlighted their vulnerability. Passage through this barren landscape was a necessary step for the ultimate completion of the quest.' WHERE distance = 1421 * 1.60934;

UPDATE goals SET description = 'Frodo, Sam, and Gollum reached the desolate plains near the heavily guarded Black Gate of Mordor. They quickly realized that this heavily guarded entrance was impassable, and their initial plan to walk directly in was a failure. The gate, a massive structure of dark iron and stone, was a symbol of Sauron''s immense power and military might. They were forced to trust Gollum''s promise of another way, a secret path through the mountains. The arrival at this impassable gate was a key event that forced them to take a new, more dangerous path, one that would lead them to the treacherous pass of Cirith Ungol.' WHERE distance = 1463 * 1.60934;

-- Next 30 entries (91-120)
UPDATE goals SET description = 'Gollum guided the hobbits to the northern edge of Ithilien, a land of verdant beauty and temporary respite. The landscape was a welcome change from the desolate plains of Mordor and the Dead Marshes. It was a place of streams and woods, a reminder of the Shire they left behind. This was a temporary sanctuary, a place where they could rest and recover from their harrowing journey. The change in landscape also served to highlight the immense contrast between the lands of good and the corrupt lands of Mordor.' WHERE distance = 1499 * 1.60934;

UPDATE goals SET description = 'Frodo and Sam were captured by a group of Gondorian Rangers led by Faramir, the younger brother of Boromir. They were taken to a hidden refuge, Henneth Annûn, where Frodo was questioned about his quest. Faramir''s moral strength was revealed at the Forbidden Pool, where he captured Gollum but then, unlike his brother, resisted the immense temptation of the Ring and allowed the hobbits to continue on their way. This act of grace and self-control provided a powerful counterpoint to Boromir''s fate and reinforced that not all Men would succumb to the Ring''s lure.' WHERE distance = 1533 * 1.60934;

UPDATE goals SET description = 'After Faramir released them, Frodo and Sam journeyed south, reaching the end of the forest, led by Gollum on their way to Cirith Ungol. The forest was a temporary sanctuary, and leaving it behind meant they were now fully committed to the dangerous journey into Mordor. The landscape was becoming more desolate and foreboding as they neared their final destination. The end of the forest was a clear sign that they were leaving the lands of good behind and entering the heart of the Enemy''s realm, a place of immense peril.' WHERE distance = 1577 * 1.60934;

UPDATE goals SET description = 'Gollum''s fragile loyalty finally broke as he led Frodo and Sam into a trap, the lair of the monstrous, ancient spider, Shelob. The dark tunnel was a place of profound darkness and terror, where Frodo was poisoned and paralyzed by her venom. In this moment, Sam emerged as an unexpected hero, and in a monumental act of courage and devotion, he fought and wounded the massive spider. The Phial of Galadriel became a literal weapon of light against this primeval darkness, proving the power of even a small token of hope.' WHERE distance = 1612 * 1.60934;

UPDATE goals SET description = 'After escaping the Tower of Cirith Ungol, Sam and Frodo, now in Mordor, found a stagnant pool of water. It was a welcome but tainted relief in the barren plains of Gorgoroth, a land that was a reflection of Sauron''s inner evil. The water was drinkable, but it was not sweet, a detail that highlighted the pervasive corruption of Mordor. This small moment of relief was a testament to the immense physical and mental toll of their journey.' WHERE distance = 1651 * 1.60934;

UPDATE goals SET description = 'Disguised in captured Orc armor, Frodo and Sam were out on the plains of Gorgoroth, drawing near the Isenmouthe, a narrow gap in the mountains. They hoped to pass unnoticed in the midst of Sauron''s armies. The land itself was a reflection of Sauron''s oppressive will, a dead, barren wasteland devoid of life and hope. The journey through this land was one of pure, grinding endurance, as the hobbits were tormented by the Ring''s weight and the ever-present threat of discovery.' WHERE distance = 1698 * 1.60934;

UPDATE goals SET description = 'This was a part of their agonizing final march toward Mount Doom, a night of grinding endurance where Frodo''s strength was at its lowest and the Ring''s power was immense. The land was dark and oppressive, with the air thick and bitter. Frodo was tormented by the Ring''s weight and was "nearly spent," unable to walk on his own. Sam''s unwavering loyalty was revealed in a monumental act of selflessness, as he physically carried Frodo up the final slopes of Mount Doom. The heroism of this final stage was not one of grand battles but of humble devotion and quiet endurance.' WHERE distance = 1755 * 1.60934;

UPDATE goals SET description = 'At the very brink of victory, in the Cracks of Doom, Frodo finally succumbed to the Ring''s power, claiming it for himself and refusing to destroy it. However, the quest was not destined to end in failure. Gollum, having followed them all the way, attacked Frodo, bit off his finger to reclaim his "Precious," and danced in triumph before accidentally falling into the chasm. The destruction of the Ring was therefore not an act of conscious will but a final, unforeseen act of "eucatastrophe" delivered by the very creature that was most obsessed with it. This final, unexpected turn of events proved that humility and providence are often the most powerful forces.' WHERE distance = 1779 * 1.60934;

UPDATE goals SET description = 'After their long journey through the barren plains of Gorgoroth, disguised as Orcs, Frodo and Sam made a tense camp along a road. Their journey was one of pure endurance, as they were constantly on the move, with little rest or food. The camp was a temporary refuge, a moment of brief, anxious slumber before they must continue their agonizing march toward Mount Doom. The landscape itself was a reflection of Sauron''s oppressive will, a dead, barren wasteland devoid of life and hope.' WHERE distance = 1798 * 1.60934;

UPDATE goals SET description = 'After being released by Faramir, Frodo and Sam made camp near Henneth Annûn, the refuge of Faramir''s Rangers. They had been questioned here before continuing their journey, and the location served as a temporary sanctuary, a place of rest and healing before they must face a new, more immediate danger. The camp was a moment of brief, anxious slumber, as they were now fully committed to the arduous journey that lay ahead, a grim reminder of the difficult path they had chosen.' WHERE distance = 1835 * 1.60934;

UPDATE goals SET description = 'Frodo and Sam continued on the Southward Road, under the guidance of Gollum, on their way to Ithilien. The road was a familiar landmark, but the journey was a new and dangerous one. The landscape was becoming more desolate and foreboding as they neared their final destination. The journey was a constant test of their skill and resolve, as they were now fully committed to the arduous journey that lay ahead.' WHERE distance = 1840 * 1.60934;

UPDATE goals SET description = 'Frodo and Sam could see Amon Dîn, a beacon hill, to the west. This sight signaled their approach to the realm of Gondor. The beacon hills, which were lit to signal for aid, were a well-known feature of Gondor. Seeing them from this part of the journey was a powerful sign of hope for the forces of good, a reminder that the world was still fighting against the shadow.' WHERE distance = 1863 * 1.60934;

UPDATE goals SET description = 'Frodo and Sam reached the landings of Osgiliath, the ruined city of Gondor. They did not enter but were taken to a hidden refuge by Faramir''s men. Osgiliath, which was once a great city, was now a desolate ruin, a symbol of the war''s destructive power. The location was a grim reminder of the immense battles that had been fought in Middle-earth. The hobbits'' passage by this ruined city was a testament to the immense peril of their journey.' WHERE distance = 1886 * 1.60934;

UPDATE goals SET description = 'The hobbits, after the destruction of the Ring, eventually reached the Gates of Minas Tirith to attend Aragorn''s coronation and be honored as heroes of the West. The city, which had been besieged by Sauron''s armies, was now a place of peace and celebration. The hobbits were no longer hiding, but were now celebrated as heroes. The return to Minas Tirith was a powerful symbol of the victory of good over evil and a testament to the immense courage of the hobbits.' WHERE distance = 1899 * 1.60934;

UPDATE goals SET description = 'On their long return journey home, the hobbits camped by a road north of the Drúadan Forest. The journey home was a literal retracing of their steps, and they were now able to travel openly, as the threat of Sauron''s evil had been lifted. The camp was a moment of rest and reflection, as they were now able to appreciate the beauty of the world they had fought to save.' WHERE distance = 1949 * 1.60934;

-- Next 30 entries (starting around distance 2000)
UPDATE goals SET description = 'The hobbits, now on their long-awaited hero''s journey home, passed the beacon on Nardol, a "Fire Hill." They were no longer hiding, but were now celebrated, a stark contrast to their secret departure. The beacons, which were once used to signal for war, were now a symbol of peace and victory. The sight of the beacons was a powerful reminder of the immense battles that had been fought and won, and a testament to the courage of those who had fought.' WHERE distance = 2000 * 1.60934;

UPDATE goals SET description = 'As they continued their long journey home, the hobbits saw the beacon hill of Minrimmon on their left, a familiar landmark on their journey as they left Gondor behind. The beacons, which were once used to signal for war, were now a symbol of peace and victory. The sight of the beacons was a powerful reminder of the immense battles that had been fought and won.' WHERE distance = 2051 * 1.60934;

UPDATE goals SET description = 'The hobbits saw the beacon tower of Calenhad, a final landmark of Gondor as they continued on their long journey home, now free from the threat of Sauron. The beacon, which was once a symbol of a desperate struggle for survival, was now a symbol of peace and victory. The sight of the beacon was a powerful reminder of the immense battles that had been fought and won, and a testament to the courage of those who had fought.' WHERE distance = 2080 * 1.60934;

UPDATE goals SET description = 'The hobbits journeyed through Rohan on their way home, passing north of the road where the Entwash river was located, a landmark on their return trip. The river was a familiar feature of the landscape, and its presence was a sign that they were nearing the end of their long journey. The journey was a long and arduous one, and the constant need to stop and rest highlighted the slow, difficult nature of their quest.' WHERE distance = 2166 * 1.60934;

UPDATE goals SET description = 'The hobbits and their companions left the Folde, a region of Rohan, on their homeward journey. The journey was a long and arduous one, and the constant need to stop and rest highlighted the slow, difficult nature of their quest. It was a journey of reflection, as they looked back on the immense battles they had fought and the friends they had lost.' WHERE distance = 2206 * 1.60934;

UPDATE goals SET description = 'The hobbits forded the Snowbourne river in Rohan as they continued on their journey home. The river was a familiar feature of the landscape, and its presence was a sign that they were nearing the end of their long journey. The journey was a long and arduous one, and the constant need to stop and rest highlighted the slow, difficult nature of their quest.' WHERE distance = 2260 * 1.60934;

UPDATE goals SET description = 'The hobbits crossed a small stream as they made their way back toward Isengard and then north. This was a small, mundane detail in the long and arduous journey, but it added to the sense of realism and the difficult terrain they had to traverse. The constant movement, with little rest, was a testament to the immense peril they had endured.' WHERE distance = 2316 * 1.60934;

UPDATE goals SET description = 'The hobbits crossed another small stream on their long journey home through Rohan. This was a small, mundane detail in the long and arduous journey, but it added to the sense of realism and the difficult terrain they had to traverse. The constant movement, with little rest, was a testament to the immense peril they had endured.' WHERE distance = 2346 * 1.60934;

UPDATE goals SET description = 'The hobbits reached the fortress of Helm''s Deep on their journey home. It was a place of recent victory for Aragorn and Rohan, and a stop on their return trip. The fortress, which was once a place of desperate struggle for survival, was now a symbol of peace and victory. The hobbits'' passage by this fortress was a testament to the immense battles that had been fought and won, and a powerful reminder of the courage of those who had fought.' WHERE distance = 2378 * 1.60934;

UPDATE goals SET description = 'The hobbits and their company reached the Treegarth of Orthanc. They saw the ruined Isengard and encountered Treebeard and the humbled Saruman on their return journey. The ruined fortress, which was once a place of immense power and evil, was now a symbol of the victory of good over evil. The hobbits'' reunion with Treebeard and their encounter with Saruman was a powerful symbol of the victory of good over evil, and a testament to the power of the Ents.' WHERE distance = 2434 * 1.60934;

UPDATE goals SET description = 'The hobbits made a temporary camp in the Gap of Rohan after leaving Isengard, continuing north toward Rivendell. The camp was a moment of brief, anxious slumber before they must continue their long journey. The journey was a long and arduous one, and the constant need to stop and rest highlighted the slow, difficult nature of their quest.' WHERE distance = 2479 * 1.60934;

UPDATE goals SET description = 'The hobbits camped by a small stream as they continued their journey north through the Gap of Rohan. This was a small, mundane detail in the long and arduous journey, but it added to the sense of realism and the difficult terrain they had to traverse. The constant movement, with little rest, was a testament to the immense peril they had endured.' WHERE distance = 2509 * 1.60934;

UPDATE goals SET description = 'The hobbits camped at the base of an out-thrust hill of Methedras, a plausible location as they continued their journey north. The camp was a temporary refuge, a moment of brief, anxious slumber before they must continue their long journey. The camp was a moment of rest and reflection, as they were now able to appreciate the beauty of the world they had fought to save.' WHERE distance = 2539 * 1.60934;

UPDATE goals SET description = 'The hobbits reached the remains of the roadway to Tharbad, a ruined city, on their journey north. The ruins were a grim reminder of the war''s destructive power. The location was a grim reminder of the immense battles that had been fought in Middle-earth. The hobbits'' passage by this ruined city was a testament to the immense peril of their journey.' WHERE distance = 2569 * 1.60934;

UPDATE goals SET description = 'The hobbits stopped at a small stream to rest as they continued their long journey home. This was a small, mundane detail in the long and arduous journey, but it added to the sense of realism and the difficult terrain they had to traverse. The constant movement, with little rest, was a testament to the immense peril they had endured.' WHERE distance = 2599 * 1.60934;

UPDATE goals SET description = 'The hobbits entered Northern Dunland, a region on their journey north toward Bree. The landscape was becoming more gentle, a sign that they were nearing the Shire. The journey was a long and arduous one, and the constant need to stop and rest highlighted the slow, difficult nature of their quest.' WHERE distance = 2629 * 1.60934;

UPDATE goals SET description = 'The hobbits drew farther and farther from the mountains and foothills as they traveled north on their way home. The landscape was a welcome change from the more treacherous terrain they had been navigating. The journey was a long and arduous one, and the constant need to stop and rest highlighted the slow, difficult nature of their quest.' WHERE distance = 2674 * 1.60934;

UPDATE goals SET description = 'The hobbits saw the marshes of the Swanfleet lying to the north as they continued their homeward journey toward Rivendell and the Shire. The marshes were a familiar feature of the landscape, and their presence was a sign that they were nearing the end of their long journey. The journey was a long and arduous one, and the constant need to stop and rest highlighted the slow, difficult nature of their quest.' WHERE distance = 2719 * 1.60934;

UPDATE goals SET description = 'The hobbits could see mists above the fens of the Swanfleet delta as they continued their journey. The mists were a familiar feature of the landscape, and their presence was a sign that they were nearing the end of their long journey. The journey was a long and arduous one, and the constant need to stop and rest highlighted the slow, difficult nature of their quest.' WHERE distance = 2759 * 1.60934;

UPDATE goals SET description = 'The hobbits reached the ruins of Ost-en-Edhil, an ancient Elven city, on their journey north. The ruins were a grim reminder of the war''s destructive power. The location was a grim reminder of the immense battles that had been fought in Middle-earth. The hobbits'' passage by this ruined city was a testament to the immense peril of their journey.' WHERE distance = 2809 * 1.60934;

UPDATE goals SET description = 'The hobbits continued east on the Moria-road, with the mountains of Moria rising ahead of them. This path was familiar from their outward journey, but it now held a different significance. The journey was a long and arduous one, and the constant need to stop and rest highlighted the slow, difficult nature of their quest.' WHERE distance = 2839 * 1.60934;

UPDATE goals SET description = 'The hobbits reached the hill where the Fellowship had sheltered from the Warg attack. This was a familiar landmark from their outward journey, but it now held a different significance. The hill, which was once a place of desperate struggle for survival, was now a symbol of peace and victory. The hobbits'' passage by this hill was a testament to the immense battles that had been fought and won.' WHERE distance = 2874 * 1.60934;

UPDATE goals SET description = 'The hobbits found themselves in open country with gentle slopes, a welcome change after their many hardships. This was a contrast to their difficult journey south, and it was a sign that they were nearing the Shire. The journey was a long and arduous one, and the constant need to stop and rest highlighted the slow, difficult nature of their quest.' WHERE distance = 2909 * 1.60934;

UPDATE goals SET description = 'The hobbits camped atop Hollin Ridge, a familiar location from their outward journey. This stop signaled their proximity to Rivendell. The camp was a temporary refuge, a moment of brief, anxious slumber before they must continue their long journey. The camp was a moment of rest and reflection, as they were now able to appreciate the beauty of the world they had fought to save.' WHERE distance = 2959 * 1.60934;

UPDATE goals SET description = 'The hobbits descended a slope to a small stream valley, nearing Rivendell and the final leg of their long journey. The descent was a sign that they were nearing a major turning point in their quest. The journey was a long and arduous one, and the constant need to stop and rest highlighted the slow, difficult nature of their quest.' WHERE distance = 3015 * 1.60934;

UPDATE goals SET description = 'The hobbits climbed northeast up a slope, seeing the end of the marsh to the west. This was a plausible detail from their journey home, as they were now able to travel openly. The end of the marsh was a sign that they were nearing the end of their long journey. The journey was a long and arduous one, and the constant need to stop and rest highlighted the slow, difficult nature of their quest.' WHERE distance = 3049 * 1.60934;

UPDATE goals SET description = 'To the west, the Loudwater (Bruinen) now ran in a deep valley, a landmark that signaled their imminent arrival at Rivendell. The river was a familiar feature of the landscape, and its presence was a sign that they were nearing the end of their long journey. The journey was a long and arduous one, and the constant need to stop and rest highlighted the slow, difficult nature of their quest.' WHERE distance = 3071 * 1.60934;

UPDATE goals SET description = 'The hobbits turned slightly west of north, adjusting their course for the final approach to the Last Homely House. This was a small, mundane detail in the long and arduous journey, but it added to the sense of realism and the difficult terrain they had to traverse. The constant movement, with little rest, was a testament to the immense peril they had endured.' WHERE distance = 3099 * 1.60934;

UPDATE goals SET description = 'The hobbits, with Gandalf and Aragorn, finally reached Rivendell, the Last Homely House. It was a place of rest and healing before they continued to the Shire. The return to Rivendell was a key event in the narrative, a final sanctuary for the hobbits before they returned to their home. The return was a powerful symbol of the victory of good over evil.' WHERE distance = 3127 * 1.60934;

UPDATE goals SET description = 'The hobbits reached the Ford of Bruinen, a familiar landmark on their journey home from Rivendell toward the Shire. The river was a familiar feature of the landscape, and its presence was a sign that they were nearing the end of their long journey. The journey was a long and arduous one, and the constant need to stop and rest highlighted the slow, difficult nature of their quest.' WHERE distance = 3135 * 1.60934;

-- Next 30 entries (3156-3991)
UPDATE goals SET description = 'The Bruinen river turned more to the south as the hobbits continued on their way back to Bree, leaving Rivendell behind them. The river was a familiar feature of the landscape, and its presence was a sign that they were nearing the end of their long journey. The journey was a long and arduous one, and the constant need to stop and rest highlighted the slow, difficult nature of their quest.' WHERE distance = 3156 * 1.60934;

UPDATE goals SET description = 'The hobbits reached the pathway to the Stone Trolls, a familiar landmark from their outward journey. This signaled their continued progress toward Bree. The trolls were a familiar feature of the landscape, and their presence was a sign that they were nearing the end of their long journey. The journey was a long and arduous one, and the constant need to stop and rest highlighted the slow, difficult nature of their quest.' WHERE distance = 3185 * 1.60934;

UPDATE goals SET description = 'The hobbits crossed the Last Bridge over the Hoarwell, a landmark from their outward journey. They were now much closer to Bree. The bridge was a familiar feature of the landscape, and its presence was a sign that they were nearing the end of their long journey. The journey was a long and arduous one, and the constant need to stop and rest highlighted the slow, difficult nature of their quest.' WHERE distance = 3199 * 1.60934;

UPDATE goals SET description = 'The hobbits traveled through open country, with the land slowly rising toward the Weather Hills ahead of them. The open country was a welcome change from the more treacherous terrain they had been navigating. The journey was a long and arduous one, and the constant need to stop and rest highlighted the slow, difficult nature of their quest.' WHERE distance = 3219 * 1.60934;

UPDATE goals SET description = 'The tops of the Weather Hills became visible, a sign of their progress as they made their way back toward Bree and a reminder of their past perils. The hills, which were once a place of desperate struggle for survival, were now a symbol of peace and victory. The hobbits'' passage by these hills was a testament to the immense battles that had been fought and won.' WHERE distance = 3234 * 1.60934;

UPDATE goals SET description = 'The Weather Hills slowly rose on the horizon as the hobbits continued their journey, nearing the location of their ambush. The hills, which were once a place of desperate struggle for survival, were now a symbol of peace and victory. The hobbits'' passage by these hills was a testament to the immense battles that had been fought and won.' WHERE distance = 3256 * 1.60934;

UPDATE goals SET description = 'Weathertop became visible straight ahead. It was a place of great significance and danger from their past journey, but now they passed it freely, as the threat of Sauron''s evil had been lifted. The hill, which was once a place of desperate struggle for survival, was now a symbol of peace and victory. The hobbits'' passage by this hill was a testament to the immense battles that had been fought and won.' WHERE distance = 3279 * 1.60934;

UPDATE goals SET description = 'The land rose slowly as the hobbits approached the hills, with Weathertop to their north. The journey was a long and arduous one, and the constant need to stop and rest highlighted the slow, difficult nature of their quest. The journey was a long and arduous one, and the constant need to stop and rest highlighted the slow, difficult nature of their quest.' WHERE distance = 3294 * 1.60934;

UPDATE goals SET description = 'The hobbits passed by Weathertop, now an unthreatening sight, as they continued their journey home along the Great East Road. The hill, which was once a place of desperate struggle for survival, was now a symbol of peace and victory. The hobbits'' passage by this hill was a testament to the immense battles that had been fought and won.' WHERE distance = 3324 * 1.60934;

UPDATE goals SET description = 'The hobbits reached the southeast edge of the Midgewater Marshes, continuing their journey back to Bree. The marshes were a familiar feature of the landscape, and their presence was a sign that they were nearing the end of their long journey. The journey was a long and arduous one, and the constant need to stop and rest highlighted the slow, difficult nature of their quest.' WHERE distance = 3359 * 1.60934;

UPDATE goals SET description = 'The hobbits camped for the night, with the marshes lying farther north from the road. They were nearing their final destination of Bree. The camp was a temporary refuge, a moment of brief, anxious slumber before they must continue their long journey. The journey was a long and arduous one, and the constant need to stop and rest highlighted the slow, difficult nature of their quest.' WHERE distance = 3391 * 1.60934;

UPDATE goals SET description = 'The hobbits camped in the stables of The Forsaken Inn, a landmark on their journey to Bree. The inn, which was once a place of desperate struggle for survival, is now a symbol of peace and victory. The hobbits'' passage by this inn is a testament to the immense battles that have been fought and won.' WHERE distance = 3423 * 1.60934;

UPDATE goals SET description = 'The hobbits arrived at The Prancing Pony in Bree, where they were welcomed as heroes. This was a stark contrast to their first, secret visit. The inn, which was once a place of great danger, was now a symbol of peace and victory. The hobbits'' return to Bree was a powerful symbol of the victory of good over evil.' WHERE distance = 3439 * 1.60934;

UPDATE goals SET description = 'The hobbits passed the Old Forest to the south as they neared the Shire. The place of their past peril was now behind them, and home was within reach. The forest, which was once a place of great danger, was now a symbol of peace and victory. The hobbits'' passage by this forest was a testament to the immense battles that had been fought and won.' WHERE distance = 3455 * 1.60934;

UPDATE goals SET description = 'The hobbits reached the Brandywine Bridge and crossed it, officially returning to the Shire after their long journey. The bridge, which was once a place of great danger, was now a symbol of peace and victory. The hobbits'' passage by this bridge was a testament to the immense battles that had been fought and won.' WHERE distance = 3479 * 1.60934;

UPDATE goals SET description = 'The hobbits arrived at the village of Frogmorton, a mundane location near the Shire, on their way to Bag End. The village, which was once a place of great danger, is now a symbol of peace and victory. The hobbits'' passage by this village is a testament to the immense battles that have been fought and won.' WHERE distance = 3501 * 1.60934;

UPDATE goals SET description = 'The hobbits finally reached Bag End, their home in the Shire. The homecoming was bittersweet, as they found it had been taken over and corrupted by Saruman''s ruffians. The home, which was once a place of great comfort, was now a symbol of the war''s destructive power. The hobbits'' passage by this home was a testament to the immense battles that have been fought and won.' WHERE distance = 3524 * 1.60934;

UPDATE goals SET description = 'The hobbits reached Stock Road, a familiar part of the Shire, as they put their home to rights during the Scouring of the Shire. The road, which was once a place of great danger, is now a symbol of peace and victory. The hobbits'' passage by this road is a testament to the immense battles that have been fought and won.' WHERE distance = 3538 * 1.60934;

UPDATE goals SET description = 'The hobbits reached the point where the road splits as they continued their journey within the Shire, or perhaps as they began their final journey. The road, which was once a place of great danger, is now a symbol of peace and victory. The hobbits'' passage by this road is a testament to the immense battles that have been fought and won.' WHERE distance = 3561 * 1.60934;

UPDATE goals SET description = 'The hobbits camped in the open lands, a final night before they reached their final destination of the Grey Havens. The camp was a temporary refuge, a moment of brief, anxious slumber before they must continue their long journey. The camp was a moment of rest and reflection, as they were now able to appreciate the beauty of the world they had fought to save.' WHERE distance = 3614 * 1.60934;

UPDATE goals SET description = 'The hobbits passed south of Tuckburrow, a location in the Shire, on their way to the Grey Havens. The village, which was once a place of great danger, is now a symbol of peace and victory. The hobbits'' passage by this village is a testament to the immense battles that have been fought and won.' WHERE distance = 3626 * 1.60934;

UPDATE goals SET description = 'Beyond the Downs were grassy, almost uninhabited lowlands, a peaceful landscape as the hobbits continued their journey toward the coast. The landscape was a welcome change from the more treacherous terrain they had been navigating. The journey was a long and arduous one, and the constant need to stop and rest highlighted the slow, difficult nature of their quest.' WHERE distance = 3639 * 1.60934;

UPDATE goals SET description = 'The hobbits reached the crest of the Far Downs, a high point from which they could see the sea and their final destination. The Downs were a familiar feature of the landscape, and their presence was a sign that they were nearing the end of their long journey. The journey was a long and arduous one, and the constant need to stop and rest highlighted the slow, difficult nature of their quest.' WHERE distance = 3669 * 1.60934;

UPDATE goals SET description = 'The hobbits could see the Tower Hills on the western horizon, a strong sign that they were nearing the Grey Havens and their final farewell. The Tower Hills were a familiar feature of the landscape, and their presence was a sign that they were nearing the end of their long journey. The journey was a long and arduous one, and the constant need to stop and rest highlighted the slow, difficult nature of their quest.' WHERE distance = 3684 * 1.60934;

UPDATE goals SET description = 'The land began to rise as the hobbits approached the Tower Hills, nearing their final destination. The journey was a long and arduous one, and the constant need to stop and rest highlighted the slow, difficult nature of their quest. The journey was a long and arduous one, and the constant need to stop and rest highlighted the slow, difficult nature of their quest.' WHERE distance = 3704 * 1.60934;

UPDATE goals SET description = 'The hobbits reached the Great East Road, a main thoroughfare that led to the Grey Havens. The road was a familiar feature of the landscape, and its presence was a sign that they were nearing the end of their long journey. The journey was a long and arduous one, and the constant need to stop and rest highlighted the slow, difficult nature of their quest.' WHERE distance = 3724 * 1.60934;

UPDATE goals SET description = 'The road reached the towers at the crest of the Tower Hills, where the hobbits would soon say their final farewells. The towers were a familiar feature of the landscape, and their presence was a sign that they were nearing the end of their long journey. The journey was a long and arduous one, and the constant need to stop and rest highlighted the slow, difficult nature of their quest.' WHERE distance = 3744 * 1.60934;

UPDATE goals SET description = 'The land dropped gently down toward the Gulf, with the port of the Grey Havens visible in the distance, a poignant sight for Frodo. The port was a familiar feature of the landscape, and its presence was a sign that they were nearing the end of their long journey. The journey was a long and arduous one, and the constant need to stop and rest highlighted the slow, difficult nature of their quest.' WHERE distance = 3764 * 1.60934;

UPDATE goals SET description = 'At the Grey Havens, the journey finally came to its bittersweet end. Frodo said his final farewells and sailed into the West on the White Ship, for he was too scarred by his long and arduous burden to find rest in Middle-earth. His departure was a powerful symbol of the true cost of heroism and sacrifice. Sam and the other hobbits, having completed their mission, were able to find peace in the restored Shire, but Frodo''s wounds, both physical and spiritual, could not be healed.' WHERE distance = 3784 * 1.60934;

UPDATE goals SET description = 'After saying farewell to Frodo, Sam, now alone, began his return journey and camped at the foot of the Tower Hills. The camp was a temporary refuge, a moment of brief, anxious slumber before he must continue his long journey. It was a moment of rest and reflection, as he was now able to appreciate the beauty of the world he had fought to save.' WHERE distance = 3814 * 1.60934;

UPDATE goals SET description = 'Sam reached the foot of the hills on his lonely journey back to the Shire. The hills were a familiar feature of the landscape, and their presence was a sign that he was nearing the end of his long journey. The journey was a long and arduous one, and the constant need to stop and rest highlighted the slow, difficult nature of their quest.' WHERE distance = 3839 * 1.60934;

-- Final entries (Sam's return journey home)
UPDATE goals SET description = 'As he continued his lonely journey, Sam saw the crest of the Far Downs to the east, a familiar landmark that signaled his return to the Shire. The Downs were a familiar feature of the landscape, and their presence was a sign that he was nearing the end of his long journey. The journey was a long and arduous one, and the constant need to stop and rest highlighted the slow, difficult nature of their quest.' WHERE distance = 3864 * 1.60934;

UPDATE goals SET description = 'Sam reached the steep western face of the Far Downs, a part of his return journey to the Shire. The Downs were a familiar feature of the landscape, and their presence was a sign that he was nearing the end of his long journey. The journey was a long and arduous one, and the constant need to stop and rest highlighted the slow, difficult nature of their quest.' WHERE distance = 3884 * 1.60934;

UPDATE goals SET description = 'Sam camped next to the road on his lonely journey back home to the Shire. The camp was a temporary refuge, a moment of brief, anxious slumber before he must continue his long journey. The camp was a moment of rest and reflection, as he was now able to appreciate the beauty of the world he had fought to save.' WHERE distance = 3904 * 1.60934;

UPDATE goals SET description = 'Sam began to see grazing lands, a familiar and welcome sight that confirmed he was nearing the Shire. The sight of the grazing lands was a powerful symbol of the peace that had returned to the world. The journey was a long and arduous one, and the constant need to stop and rest highlighted the slow, difficult nature of their quest.' WHERE distance = 3919 * 1.60934;

UPDATE goals SET description = 'Sam reached Michel Delving, the capital of the Shire, on his return journey. The town, which was once a place of great danger, is now a symbol of peace and victory. The journey is a long and arduous one, and the constant need to stop and rest highlighted the slow, difficult nature of their quest.' WHERE distance = 3934 * 1.60934;

UPDATE goals SET description = 'Sam came to Waymeet, a location within the Shire, on his way back to Bag End. The village, which was once a place of great danger, is now a symbol of peace and victory. The journey is a long and arduous one, and the constant need to stop and rest highlighted the slow, difficult nature of their quest.' WHERE distance = 3969 * 1.60934;

UPDATE goals SET description = 'Sam finally arrived back at Bag End at sunset, having completed his long and arduous journey and found his place as a hero of the Shire. He was no longer just a gardener, but a hero of the age. His homecoming was a bittersweet moment, as he was now alone, but he was also a symbol of hope for the future. He had returned to his home, but he was forever changed by the journey.' WHERE distance = 3991 * 1.60934;

-- Update special field values for entries that have them
UPDATE goals SET special = 'The Prancing Pony' WHERE distance = 135 * 1.60934;
UPDATE goals SET special = 'Weathertop' WHERE distance = 241 * 1.60934;
UPDATE goals SET special = 'Reach Rivendell - Challenge 1 End' WHERE distance = 458 * 1.60934;
UPDATE goals SET special = 'Redhorn Pass' WHERE distance = 750 * 1.60934;
UPDATE goals SET special = 'Moria' WHERE distance = 798 * 1.60934;
UPDATE goals SET special = 'Meet Galadriel - Challenge 2 End' WHERE distance = 920 * 1.60934;
UPDATE goals SET special = 'Orc Attack' WHERE distance = 1267 * 1.60934;
UPDATE goals SET special = 'The Breaking of the Fellowship - Challenge 3 End' WHERE distance = 1309 * 1.60934;
UPDATE goals SET special = 'The Black Gate' WHERE distance = 1463 * 1.60934;
UPDATE goals SET special = 'Shelob''s Lair' WHERE distance = 1612 * 1.60934;
UPDATE goals SET special = 'Chasm of Doom - Challenge 4 End' WHERE distance = 1779 * 1.60934;
UPDATE goals SET special = 'Aragorn''s Coronation - Challenge 5 End' WHERE distance = 1899 * 1.60934;
UPDATE goals SET special = 'Entwash River' WHERE distance = 2166 * 1.60934;
UPDATE goals SET special = 'Destroyed Isengard - Challenge 6 End' WHERE distance = 2434 * 1.60934;
UPDATE goals SET special = 'Tharbad Roadway' WHERE distance = 2569 * 1.60934;
UPDATE goals SET special = 'Swanfleet Marshes' WHERE distance = 2719 * 1.60934;
UPDATE goals SET special = 'Hollin Ridge' WHERE distance = 2959 * 1.60934;
UPDATE goals SET special = 'Return to Rivendell - Challenge 7 End' WHERE distance = 3127 * 1.60934;
UPDATE goals SET special = 'Back Home - Challenge 8 End' WHERE distance = 3524 * 1.60934;
UPDATE goals SET special = 'Final Farewell - Challenge 9 End' WHERE distance = 3784 * 1.60934;
UPDATE goals SET special = 'Closing Credits' WHERE distance = 3991 * 1.60934;
