-- Migration number: 0011 	 2026-01-12T00:00:00.000Z

-- Batch 01: Update goal descriptions for improved accuracy (Goals 4-8)

-- Goal: Reach Stock Road (Distance: 15)
UPDATE goals SET description = 'Before the fear of the road truly set in, the hobbits wandered through the winding lanes and hedgerows of the Green Hill Country. The journey took them deep into the heart of Tookland, where the air was still filled with the comfortable, earthy familiarity of the Shire. Yet, as they pressed on towards the Stock Road, the safety of Bag End felt increasingly distant. They were no longer merely walking boundaries; they were stepping out of their known world into the wider, wilder lands.' WHERE distance = 15 * 1.60934;

-- Goal: Encounter with Black Rider (Distance: 32)
UPDATE goals SET description = 'The peaceful solitude of the road was shattered by a sound that would soon haunt Frodo''s nightmares: the rhythmic clatter of hoofbeats approaching from behind. Scrambling to hide amidst the roots of an old oak tree, the hobbits watched in terror as a black-cloaked figure halted mere feet away, sniffing the air for the scent of the Ring. It was their first brush with the shadow that hunted them, transforming their walk from a departure into a desperate flight. The chill of the Rider''s presence lingered in the twilight long after it had passed.' WHERE distance = 32 * 1.60934;

-- Goal: Meet Elves (Distance: 41)
UPDATE goals SET description = 'Just as the dread of the Riders threatened to overwhelm them, a clear voice rose in song beneath the stars, invoking the name of Elbereth Gilthoniel. In the woods above Woodhall, they stumbled upon Gildor Inglorion and a company of High Elves, a meeting of chance that felt like a miraculous blessing. Under the starlight, they shared white bread and fragrant wine, finding a brief but profound sanctuary against the gathering dark. For one night, the ancient beauty of the Elder Days held the terror at bay.' WHERE distance = 41 * 1.60934;

-- Goal: Reach Farmer Maggot''s Field (Distance: 61)
UPDATE goals SET description = 'To avoid the watched roads, the travellers cut across the damp, foggy fields of the Marish, landing them squarely in the territory of Farmer Maggot. Though Frodo initially trembled at the memory of Maggot''s gripping dogs, he found instead a stout hospitality at Bamfurlong that defied his childhood fears. Over a hearty supper of mushrooms and bacon, they found an unexpected ally who offered not only news of the pursuing Riders but a covered wagon to speed them towards the river.' WHERE distance = 61 * 1.60934;

-- Goal: Cross on the Buckleberry Ferry (Distance: 70)
UPDATE goals SET description = 'With the mist rising from the Brandywine River, the hobbits hurriedly boarded the small flat-boat of the Buckleberry Ferry. As they pushed off into the slow, dark current, leaving the Shire bank behind, a solitary, cloaked figure crawled onto the landing stage they had just departed. They crossed into Buckland not a moment too soon, the safety of the swift-flowing water acting as a barrier against the Black Rider''s grasp. Safe for now, they looked back at the darkening shore they had fled.' WHERE distance = 70 * 1.60934;

-- Goal: Reach Crickhollow (Distance: 73)
UPDATE goals SET description = 'Safe in Buckland, you arrive at the cozy house in Crickhollow where Fredegar Bolger has prepared a steaming bath and a hearty supper. This dwelling was meant to be a quiet retreat, but instead becomes the setting where a conspiracy of friends is unmasked. Merry and Pippin reveal they know the secret of the Ring and refuse to let Frodo leave without them. It is a final night of warmth and companionship before you must slip through the hedge and into the looming shadows of the Old Forest.' WHERE distance = 73 * 1.60934;

-- Goal: Reach the top of a knoll in the Old Forest. Surrounded by Trees (Distance: 87)
UPDATE goals SET description = 'The paths of the Old Forest feel alive, constantly shifting to steer you away from your northward course and deeper into the stifling heart of the woods. Oppressed by the heat and the sensation of hostile, watching eyes, you climb a steep, bald knoll hoping to spot the East Road. Instead of a way out, you see only a sea of swaying leaves and the distant Barrow-downs, realizing with dread that you are being herded toward the River Withywindle.' WHERE distance = 87 * 1.60934;

-- Goal: See Old Man Willow (Distance: 95)
UPDATE goals SET description = 'The path drops into the drowsy Withywindle valley, where the air is hot and heavy, luring the travelers to rest beneath a massive grey willow. This ancient tree suddenly reveals its malice, trapping Merry and Pippin within its wooden cracks and resisting all of Sam and Frodo''s desperate attempts to free them. You are held fast by the Great Willow''s power, caught in a nightmarish struggle against the spirit of the Old Forest itself.' WHERE distance = 95 * 1.60934;

-- Goal: Tom Bombadil''s House (Distance: 98)
UPDATE goals SET description = 'Emerging from the malice of the Old Forest, you find immediate sanctuary in the house of Tom Bombadil, where the air is sweet with the scent of apples and woodsmoke. Golden light bathes the room as Tom''s booming songs and Goldberry''s rain-clear laughter drive away the lingering shadow of the Willow''s grasping roots. Here, with a supper of yellow cream and honeycomb set before you, the fears of the outside world feel distant and powerless, barred from this blessed place of ancient, merry peace.' WHERE distance = 98 * 1.60934;

-- Goal: The Hobbits are captured by Wights (Distance: 115)
UPDATE goals SET description = 'A thick, blinding fog rolls down from the cold heights, separating you from your companions amidst the menacing standing stones of the Barrow-downs. Panic sets in as the mist swirls into phantom shapes, and suddenly a freezing, undeniable grip seizes you, dragging you helplessly down into the dark earth. You awaken in the profound blackness of a barrow, clad in white and surrounded by the scent of ancient decay, as a long, pale arm creeps toward the sword lying across your defenseless necks.' WHERE distance = 115 * 1.60934;

-- Goal: Reach Bree and meet Strider (Distance: 135)
UPDATE goals SET description = 'After the cold terrors of the Barrow-downs, the warm lights of The Prancing Pony offer a welcome, though crowded, sanctuary in Bree. The common room is alive with the din of Men and Hobbits, the air thick with pipe-smoke and the comforting heat of a roaring fire. Yet, amidst the clatter of mugs and cheerful songs, your gaze is drawn to a weather-beaten Ranger sitting silently in a dark corner, known only as Strider, whose watchful eyes suggest he knows much of your perilous business.' WHERE distance = 135 * 1.60934;

-- Goal: Camp in Chetwood, East of Archet (Distance: 147)
UPDATE goals SET description = 'Under Strider''s grim guidance, you veer away from the Road to evade the Black Riders, striking north into the tangled and pathless Chetwood. The Ranger leads you swiftly through the thickening trees, choosing a winding course to confuse any pursuit, his silent confidence contrasting with your own anxious stumbling. As twilight deepens, you make a fireless camp in a hidden dell, listening to the wind in the branches and feeling the heavy weight of the unseen hunters behind you.' WHERE distance = 147 * 1.60934;

-- Goal: Leave the Chetwood (Distance: 165)
UPDATE goals SET description = 'The last distinct trees of the Chetwood fade behind you, giving way to a bleak and featureless expanse of boggy land. Strider leads you relentlessly downward from the ridge, and soon the ground turns soft and treacherous beneath your boots as you approach the Midgewater Marshes. The air grows still and damp under a grey, cheerless sky, hinting at the difficult slog that lies ahead. Even as the biting insects begin to rise from the fen, the Ranger maintains his steady pace, urging the company forward into the deepening gloom.' WHERE distance = 165 * 1.60934;

-- Goal: Camp in Western Marshes (Distance: 179)
UPDATE goals SET description = 'The ground has become boggy and shifting, offering no dry place to lie, while the air fills with the incessant biting of midges that rise from the stagnant pools. As night falls upon the cheerless western expanse, you hudde on a patch of damp tussocks, listening to the maddening *neeqr-breek* of unseen creatures in the reeds. There is little rest to be found here, only a cold, wet vigil under a starless sky as the mist thickens around you. Every step has been a struggle against the sucking mire, and sleep comes only fitfully amidst the noise of the fen.' WHERE distance = 179 * 1.60934;

-- Goal: Reach Eastern edge of the Midgewater Marshes (Distance: 198)
UPDATE goals SET description = 'At last, you stumble out from the reeking gloom of the Midgewater Marshes, the ground beneath your feet turning from treacherous slime to firm, dry turf. The torment of the biting midges fades behind you as the air grows clearer, revealing the rising line of the Weather Hills and the distant, jagged peak of Weathertop awaiting your approach. Though the crossing has been a miserable slog of mud and weariness, you have conquered the fen, and the sight of solid land offers a profound sense of relief after the days of stagnant struggle.' WHERE distance = 198 * 1.60934;

-- Goal: Camp by a stream, among stunted Alder trees (Distance: 211)
UPDATE goals SET description = 'At last, the reeking fens of the Midgewater Marshes give way to firmer, rising ground, leading you to a campsite beside a clear-flowing stream. A few stunted alder trees stand guard along the banks, their gnarled roots drinking from the water while their gray branches rattle in the breeze. It is a relief to rest on dry earth, listening to the stream''s clean song instead of the buzz of marsh-flies. To the east, the Weather Hills loom ever larger, their ridges dark and watchful under the starlit sky.' WHERE distance = 211 * 1.60934;

-- Goal: Camp at the foot of the Weather Hills (Distance: 229)
UPDATE goals SET description = 'The land becomes bleak and barren as you approach the Weather Hills, a ridge of weather-worn slopes that rise like a broken wall against the sky. Ahead, the ruins of Amon Sûl crown the highest peak, Weathertop, standing as a silent and ominous sentinel over the deepening twilight. The air grows heavy with a sense of unseen eyes watching from the shadows, and every rustle of the wind sounds like a stealthy footstep. You make a cold camp in a hollow at the hills'' feet, the sense of dread growing stronger as the darkness gathers around the ancient, crumbled stones.' WHERE distance = 229 * 1.60934;

-- Goal: Attacked by Nazgul on Amon Sûl (Weathertop) (Distance: 241)
UPDATE goals SET description = 'Cold dread descends upon the summit of Amon Sûl as five tall figures close in from the darkness, their eyes gleaming with a hateful, chilly light. Overcome by terror, you slip on the Ring, only to reveal yourself to the pale shapes that lunge with piercing cries. The Witch-king strikes with a Morgul blade, spreading a deadly numbness through your shoulder, just as Strider leaps from the shadows with flaming brands to drive the shrieking Wraiths back into the night.' WHERE distance = 241 * 1.60934;

-- Goal: Camp in thickets south of the Great East Road (Distance: 260)
UPDATE goals SET description = 'The flight from Weathertop is a desperate scramble into the wild, burdened heavily by Frodo''s worsening wound and the lingering chill of the Morgul-blade. Strider guides you relentlessly through the pathless lands south of the Great East Road, avoiding the open way where the Black Riders surely hunt. Every mile is a struggle against fear and exhaustion as you push through tangled thickets and rough terrain, seeking only to hide from the Enemy''s gaze. There is no rest here, only the driving need to reach Rivendell before the shadow claims the Ring-bearer.' WHERE distance = 260 * 1.60934;

-- Goal: Camp (Distance: 271)
UPDATE goals SET description = 'The camp is pitched in a cheerless hollow beneath the weather-stained hills, offering only a fragile concealment from the emptiness of the night. A damp mist clings to the ground, and the fire is kept small and low, its warmth barely reaching those who huddle close. Frodo lies pale and restless, the chill of the Morgul-wound spreading through his shoulder, while Strider keeps a ceaseless watch, his grim face turned ever towards the shadows that stretch from the East.' WHERE distance = 271 * 1.60934;
