-- Migration number: 0013 	 2026-01-12T00:00:00.000Z

-- Batch 03: Update goal descriptions for improved accuracy

-- Goal: Reach the top of another low mountain spur, descending in a Southwest direction (Distance: 544)
UPDATE goals SET description = 'The Company trudged across the bleak and empty lands of Eregion, where the stones were often stained as if with ancient blood. To the east, the Misty Mountains rose like a sheer wall, dominated by the cruel, snow-clad peak of Caradhras. Upon cresting a rugged spur of red rock, the travellers found no respite from the biting wind, only another descent into a shallow, barren valley. Gandalf led them on a south-westerly course towards the roots of the mountains, his eyes frequently scanning the pale sky for any sign of spies.' WHERE distance = 544 * 1.60934;

-- Goal: Path comes to a steep drop-off, go along cliff top (Distance: 548)
UPDATE goals SET description = 'The Fellowship reaches an abrupt precipice where the ridge they are traversing falls sheer into a deep trough of the land. Aragorn scouts the jagged edge, leading the Company along the cliff top where the reddish stones of Hollin lie tumbled and broken. The wind blows cold from the mountains in the east, chilling the hobbits as they carefully pick their way along the high ground. Below them, the faint noise of running water hints at the stream they must cross once a descent is found.' WHERE distance = 548 * 1.60934;

-- Goal: Cross a small stream (Distance: 560)
UPDATE goals SET description = 'The Fellowship descends into a shallow trough of the land to ford a small stream that winds through the red stones of Eregion. Aragorn tests the footing on the slippery rocks, guiding the Hobbits through the cold, chattering water while Legolas watches the skyline with keen eyes. All around them, ancient holly-trees stand like silent sentinels, remnants of the people who once dwelt in this now-desolate realm. The travellers hurry across the open streambed, oppressed by the silence and the growing sense that they are being tracked by something unseen.' WHERE distance = 560 * 1.60934;

-- Goal: Cross another small stream which flows West to a swampy area (Distance: 588)
UPDATE goals SET description = 'The Fellowship splashes through yet another watercourse in the empty lands of Eregion, where the ground grows increasingly soft and treacherous. This stream runs swiftly towards the west, disappearing into a deepening gloom of swampy lowlands that lie off their path. Aragorn keeps a steady pace, wary of the silence that broods over these ancient stones, while the hobbits struggle to keep their footing on the slick, wet banks.' WHERE distance = 588 * 1.60934;

-- Goal: Reach a hilltop, turning Southeast (Distance: 608)
UPDATE goals SET description = 'The Fellowship crests a wind-swept hill and halts to survey the empty lands of Eregion stretching out on all sides. Far ahead, the peaks of the Misty Mountains rise like a sheer wall, with the Redhorn Gate visible as a distant notch. Aragorn adjusts their bearing, leading the group southeast towards the mountain roots rather than continuing south. The stones here seem heavy with silence, offering no welcome to the travellers in this land forsaken by the Elves.' WHERE distance = 608 * 1.60934;

-- Goal: Cross a small stream (Distance: 627)
UPDATE goals SET description = 'The Company splashes through a shallow, chilly brook that winds its way through the empty lands of Eregion. Aragorn leads them cautiously, for although the stones of Hollin are not evil, the deep silence of the territory feels heavy and expectant. No birds sing in the thickets along the bank, and the wind sighs lonely over the withered bracken. It is a quiet land that seems to hold its breath, remembering the High Elves who dwelt here long ago before the dark days came.' WHERE distance = 627 * 1.60934;

-- Goal: Rolling Lands (Distance: 638)
UPDATE goals SET description = 'The Company trudges through the rolling country of Hollin, climbing ridge after ridge that rise like waves against the feet of the Misty Mountains. Gandalf leads them steadily southward across the cold and empty land, where the only sound is the wind sighing over the stones and withered bracken. Though the ancient realm of the Elven-smiths lies silent and deserted, Aragorn often casts a wary eye towards the sky, anticipating the spies of the Enemy. Ahead, the cruel peak of Caradhras glints white and watchful, marking the perilous path they must soon attempt.' WHERE distance = 638 * 1.60934;

-- Goal: Land drops more steeply, go Southeast into a valley (Distance: 668)
UPDATE goals SET description = 'The Company traversed the rugged red lands of Hollin, marching beneath a clear and pale sun. As the day wore on, the ground fell away sharply towards the south-east, forcing the travellers to pick their way carefully down the steep slopes. Aragorn led them into a deep valley where the wind was less biting, though the sense of ancient emptiness remained heavy upon the air. In this desolate country, the stones themselves seemed to mourn the departure of the Elven-smiths who had dwelt here long ago.' WHERE distance = 668 * 1.60934;

-- Goal: Cross a small stream (Distance: 675)
UPDATE goals SET description = 'The Fellowship picks their way down the steepening slopes of Hollin into a shallow valley, at the bottom of which a small stream flows over a stony bed. Aragorn leads the group across the chilly water, stepping carefully on the slippery rocks, while Gimli and the hobbits follow close behind. Beyond the ford, the ground rises sharply once more, climbing towards a ridge that looms against the northern sky. A strange silence lies over this empty land of Eregion, making even the splash of their boots in the stream sound unnaturally loud.' WHERE distance = 675 * 1.60934;

-- Goal: Climb up North side of Hollin ridge (Distance: 686)
UPDATE goals SET description = 'The Fellowship ascends the steep, heather-covered slopes of the ridge, their boots crunching on loose stones as they climb. To the west, the land of Hollin falls away in brown undulations, seemingly empty of all living things. Aragorn presses forward with urgency, seeking the high ground to survey the path towards the distant mountains. The silence of Eregion feels heavy here, an ancient quiet that seems to hold its breath as the travellers pass.' WHERE distance = 686 * 1.60934;

-- Goal: Top of Hollin Ridge. Crebain fly over. - Border of Eregion (Distance: 690)
UPDATE goals SET description = 'Samwise Gamgee points out a strange, flying shadow moving against the wind, which Legolas swiftly identifies as a regiment of Crebain from Dunland. At Aragorn''s urgent cry, the Company scrambles frantically into the deep heather and hollows of the red stone, pressing themselves flat to escape detection. The air fills with the rushing sound of wings and harsh, croaking cries as the black crows wheel overhead, searching the land for intruders. Fear grips the travellers as they lie motionless, listening to the spies of Saruman pass dangerously close to their hiding place.' WHERE distance = 690 * 1.60934;

-- Goal: Sense something flying overhead before dawn. Cross a small stream (Distance: 708)
UPDATE goals SET description = 'The Fellowship continues their forced march through the night, keeping to the low valleys to avoid the gaze of Saruman''s spies. Just before the cold dawn breaks, Frodo shivers as he senses a dark, winged shape pass high overhead, silent and watchful against the dim stars. Aragorn hurries the weary group across a small, chattering stream, anxious to reach the cover of a dense holly thicket on the far bank. Though the sky remains empty to the eye, the feeling of being hunted weighs heavily on the Company as they settle into hiding for the day.' WHERE distance = 708 * 1.60934;

-- Goal: Road climbs higher (Distance: 733)
UPDATE goals SET description = 'The Company toiled upwards, their path becoming a strenuous climb as they approached the knees of the mountains. On their left stood the darker heights, while the Redhorn, cruel Caradhras, reared its snowy head directly before them. Vegetation grew sparse and stunted in the thinning air, marking their departure from the living lands of Hollin into a cold world of stone and grey skies. With every mile, the travellers felt the weight of the peaks bearing down upon them, a silent threat watching their slow progress towards the high pass.' WHERE distance = 733 * 1.60934;

-- Goal: Almost at the foot of the Redhorn. Gandalf and Aragorn debate the path. Fearing snow everyone carries wood (Distance: 742)
UPDATE goals SET description = 'The Fellowship trudges up long, bleak slopes until they stand almost at the very foot of the Redhorn, the cruel peak known as Caradhras. Here the path creates a sharp debate between Gandalf and Aragorn, who weigh the risks of the high pass against other darker roads. Fearing the grey clouds gathering about the mountain''s crown, the travellers heed a warning to prepare for bitter cold. Each member of the Company adds a heavy bundle of wood to their gear, accepting the burden as their only hope against the threatened snows.' WHERE distance = 742 * 1.60934;

-- Goal: Redhorn pass. Snow falling thickly, cannot go further. - Caradhras (Distance: 750)
UPDATE goals SET description = 'The Fellowship''s ascent of Caradhras is brought to a freezing halt by a blizzard that buries the path under impassable mounds of snow. While the hobbits huddle against the cliff face for warmth, Aragorn and Boromir valiantly attempt to plough a way through the drifts, but the mountain''s malice proves too great. Even Gandalf''s magic cannot quell the storm, and the travellers are forced to admit defeat on the high pass. With the way forward completely blocked, the Company has no choice but to turn around and begin a perilous descent back towards the Hollin Ridge.' WHERE distance = 750 * 1.60934;

-- Goal: Back down the pass, turn West away from the path. Crebain return (Distance: 754)
UPDATE goals SET description = 'The Company, having been defeated by the malevolence of Caradhras, began the weary descent back towards the lower lands of Hollin. Boromir and Aragorn ploughed a path through the deep drifts while the hobbits struggled against the biting cold, their hopes of a high pass buried under the heavy snow. Upon reaching the foothills, the travellers turned westwards, forsaking the Redhorn Gate for the uncertainty of the wilderness once more. Though the storm had ceased, the grey skies felt oppressive, and the fear of returning Crebain urged them to seek the shadows of the cliffs rather than the open road.' WHERE distance = 754 * 1.60934;

-- Goal: Climb to the top of a hill, attack by Wargs (Distance: 778)
UPDATE goals SET description = 'Forced to retreat from the cruel snows of Caradhras, the Company sought a defensible position atop a small hillock as the howling of Wargs encircled them in the darkness. The wolves, led by a great chieftain whom Legolas silenced with a swift arrow, pressed close until Gandalf rose and ignited the surrounding trees with a flash of his staff. Fire leapt from branch to branch in a dazzling display that drove the fell beasts back into the shadows, saving the travellers from being overrun. Though the dawn brought safety, the Fellowship knew their secrecy was lost and they must now race towards the hidden Doors of Durin.' WHERE distance = 778 * 1.60934;

-- Goal: Gates of Khazad-dûm (Reach the doors of Moria) (Distance: 798)
UPDATE goals SET description = 'The Company of the Ring followed the dried-up bed of the Sirannon until they reached a dark, still lake gathered beneath the sheer cliffs of the Misty Mountains. Here stood the Doors of Durin, flanked by two great holly trees, their silver lines revealed only by moonlight and Gandalf''s command. For a long while the wizard struggled with the riddle etched upon the stone, while an ominous ripple disturbed the silence of the water behind them. Just as Gandalf spoke the password Mellon and the doors swung outward, the Watcher in the Water surged forth to seize Frodo. The travellers scrambled into the mines, and the great stone doors crashed shut behind them, burying them in the deep dark of Moria.' WHERE distance = 798 * 1.60934;

-- Goal: Reach junction of 3 passages with guardroom (Distance: 818)
UPDATE goals SET description = 'The Company trudged through the oppressive dark of Khazad-dûm for many weary hours before stumbling upon a wide archway opening into an ancient guardroom. Inside the chamber, a deep well was cut into the rock floor, and three arched passages led away into the gloom, presenting Gandalf with a difficult choice of direction. While the wizard pondered the way, Peregrin Took, overcome by curiosity, dropped a loose stone into the well, the long silence eventually broken by a faint plunk far below. The quiet was then ominously disturbed by a rhythmic hammering from the depths, a tom-tap-tom that signalled something in the deep places had been awakened by the hobbit''s foolishness.' WHERE distance = 818 * 1.60934;

-- Goal: Find Balin's tomb. Attacked by orcs and a troll (Distance: 838)
UPDATE goals SET description = 'The Company discovered the high Chamber of Mazarbul, where a single shaft of light illuminated the white stone slab of Balin''s tomb. Gandalf deciphered the harrowing final scribbles in the Book of Mazarbul, reading of the drums in the deep and the shadow that moved in the dark. Their sombre reading was shattered by the rhythmic doom, doom of drums and the crash of orcs and great cave-trolls assailing the doors. In the fierce skirmish that followed, a chieftain spearheaded the attack, striking Frodo with a heavy blow that was miraculously turned by his secret coat of mithril mail.' WHERE distance = 838 * 1.60934;
