-- Migration number: 0014 	 2026-01-12T00:00:00.000Z

-- Batch 04: Update goal descriptions for improved accuracy

-- Goal: Escape from Moria, reach the spring of the Silverlode (Distance: 842)
UPDATE goals SET description = 'The Company bursts from the Great Gates into the dim light of the Dimrill Dale, their hearts shattered by the wizard''s fall into the abyss. Aragorn rouses the weeping hobbits from their grief, urging them away from the shadow of the mountain before orcs can pursue them. They race down the worn stone steps to where the Mirrormere lies dark and still, reflecting the Crown of Durin in its depths. Beside the bubbling spring of the Silverlode, the travellers pause only for a moment to breathe the free air, their eyes turning towards the distant, golden woods of Lothlórien.' WHERE distance = 842 * 1.60934;

-- Goal: Enter woods of Lothlorien (Distance: 855)
UPDATE goals SET description = 'The remaining members of the Company follow the Silverlode stream down from the mountains until the trees of the Golden Wood rise up to meet them. Legolas speaks of Lothlórien with reverence, yet Boromir fears the legends of the sorceress who dwells within. Stepping beneath the eaves, the travellers find the light has changed, no longer the grey of winter but a golden hue that seems trapped within the leaves. The air itself feels different here, healing and ancient, as the weariness of Moria begins to lift in the presence of an elder magic.' WHERE distance = 855 * 1.60934;

-- Goal: Cross the Silverlode on ropes (Distance: 861)
UPDATE goals SET description = 'Guided by Haldir and his wardens, the Company reached the banks of the Silverlode, the river Celebrant, which flowed cold and swift from the mountains. To continue into the heart of the Golden Wood, the travellers had to cross the rushing water upon slender grey ropes strung between the great trees on either bank. Legolas moved across the swaying cord with elven grace, but for the hobbits, specifically Samwise, the crossing proved a terrified ordeal of clinging hands and shuffling feet. Once safely on the far side, they stood within the Naith of Lórien, surrounded by the towering mallorn-trees that would shelter them from the outside world.' WHERE distance = 861 * 1.60934;

-- Goal: Reach the hill of Cerin Amroth (Distance: 906)
UPDATE goals SET description = 'The Company walked through the open glades of the Golden Wood, marvelling at the mallorn-trees that towered like living pillars of silver and gold. As the path wound deeper into Lothlórien, the weary travellers approached a great mound covered in the pale winter flowers of niphredil and elanor. This was Cerin Amroth, the heart of the ancient realm, rising green and fair above the surrounding forest floor. Frodo felt a timeless peace wash over him, as if the shadow of the outside world had no power to touch this high and holy place.' WHERE distance = 906 * 1.60934;

-- Goal: Reach Cerin Amroth and meet Celeborn and Galadriel (Distance: 920)
UPDATE goals SET description = 'The travellers are led from the mound of Amroth to the great city of Caras Galadhon, a fortress of green towers illuminated by countless silver lamps. Climbing the white ladders of the mightiest mallorn, they are brought before the Lord Celeborn and the Lady Galadriel in their high chamber. In the Lady''s gaze, which seems deeper than the sea, each member of the Fellowship feels their mind searched and their secret desires laid bare. Here, amidst the ancient power of the Elves, the Company is granted sanctuary for a time, finding rest within the heart of the Golden Wood.' WHERE distance = 920 * 1.60934;

-- Goal: Leave Caras Galadon and walk to a grassy lawn on the Silverlode west of the river Anduin. Celeborn and Galadriel give you boats, and present gifts to everyone (Distance: 930)
UPDATE goals SET description = 'The Company departs from the City of the Galadhrim, guided through the golden woods to a green tongue of land where the silver waters of the Celebrant meet the great River Anduin. Here, upon a lawn of smooth grass, the Elves prepare the slight grey boats that will carry the travellers on the next stage of their journey. As they prepare to embark, the Lady Galadriel approaches on a ship shaped like a great white swan, gliding silently out of the mist to bid them farewell. On this final parting, the Lord and Lady present each member of the Fellowship with gifts of power and beauty unique to their needs, arming them with hope for the darkening road ahead.' WHERE distance = 930 * 1.60934;

-- Goal: Camp in woods on west bank of the river (Distance: 951)
UPDATE goals SET description = 'The Fellowship drifted slowly down the Great River Anduin, the golden light of Lothlórien fading into memory behind them. As twilight deepened, Aragorn signalled for the small fleet of grey elven-boats to make for the western bank, where the trees offered coverage from watching eyes. The company drew their vessels up onto the muddy shore and established a quiet camp beneath the dark boughs of the river-woods. Sleep came slowly that first night away from the protection of Galadriel, with only the murmuring flow of the Anduin to mark the passing hours.' WHERE distance = 951 * 1.60934;

-- Goal: Camp on west bank of river (Distance: 987)
UPDATE goals SET description = 'The Company steered their grey elven-boats to the western shore of the Anduin as the light faded from the sky. They found a camping spot on a low bank where the trees were beginning to thin, appearing stunted and twisted compared to the golden woods they had left behind. Aragorn set a watch, his eyes scanning the eastern bank where the Brown Lands lay in shadowy silence, barren and treeless. The sanctuary of Lórien felt like a distant memory, replaced by the cold reality of the river''s widening course and a growing dread that their movements were being tracked from the far shore.' WHERE distance = 987 * 1.60934;

-- Goal: The trees thin out, it is grey and overcast (Distance: 1008)
UPDATE goals SET description = 'The Company continues their journey down the Anduin, but the comforting shelter of the woods begins to fail. On the western bank, the trees thin out and fade into scattered tussocks of grey grass, leaving the travellers exposed under a vast, overcast sky. To the east, the Brown Lands rise bleak and wold-like, a withered landscape scoured by ancient wars, devoid of any sign of life. The air hangs heavy and still, pressing down upon the small fleet of boats as they drift through this desolate stretch of the river.' WHERE distance = 1008 * 1.60934;

-- Goal: Camp on flats north of the Field of Celebrant (Distance: 1023)
UPDATE goals SET description = 'The Company guided their grey boats along the widening Anduin, passing into a desolate region where the banks stretched out into featureless flats. To the west lay the grass-lands of the Field of Celebrant, while the east offered only the withered, windy expanse of the Brown Lands. Under a cold grey sky that mirrored the dreary water, the travellers pulled ashore on the western bank to make camp, finding little shelter on the open plains. The silence of the empty lands pressed in on them, unbroken by bird or beast, amplifying the watchful unease that had settled over the Fellowship.' WHERE distance = 1023 * 1.60934;

-- Goal: River broadens, continues grey and overcast (Distance: 1040)
UPDATE goals SET description = 'The Company drifted steadily southward as the Great River broadened into a wide, grey expanse reflecting the overcast sky above. On either bank, the land lay flat and featureless, offering no shelter to the small boats that seemed terribly exposed on the open water. The world seemed drained of colour, with even the distant trees appearing as mere smudges against the horizon. This monotonous stretch of the Anduin tested their patience, the silence broken only by the dip of paddles as they navigated the bleak and sullen waters.' WHERE distance = 1040 * 1.60934;

-- Goal: Reach North Undeep with stony beaches on east – gravel shoals in the water: go carefully (Distance: 1063)
UPDATE goals SET description = 'The Company arrived at the North Undeep, where the channel of the Great River became shallow and fraught with danger. Aragorn signalled for caution as they navigated past the gravel shoals that lurked beneath the surface, steering the boats close to the stony beaches on the eastern bank. To their left lay the withered and scorched expanses of the Brown Lands, stretching away endlessly under the grey, overcast sky. The boats moved slowly through the treacherous water, every splash sounding loud in the oppressive silence of the desolate river valley.' WHERE distance = 1063 * 1.60934;

-- Goal: River Limlight enters on west (Distance: 1070)
UPDATE goals SET description = 'The Company navigated their flotsam of boats into the swifter current as the Anduin deepened beyond the stony shoals of the North Undeep. From the west, the rushing waters of the River Limlight poured into the Great River, marking the final boundary of the Field of Celebrant. The trees of Lothlórien fell away behind them, replaced by the brown and withered grass of the Wold of Rohan that rose in steep, treeless slopes. Frodo felt the protection of the Elves slip away as the boats were borne rapidly southward under a cold and uncovering sky.' WHERE distance = 1070 * 1.60934;

-- Goal: Sam spots Gollum on Log (Distance: 1075)
UPDATE goals SET description = 'The Company drifts silently down the Great River Anduin, the grey water swirling past their small fleet of elven boats. During a night watch, Sam notices a dark shape floating behind them, looking like a log with eyes, which he realises is Gollum trailing them. Though Aragorn has been aware of the creature''s pursuit since they left Lothlórien, this confirmation chills the hobbits as they drift under the pale moon. The creature paddles with soft, splashing hands, keeping distance but never losing sight of the Ring-bearer on the moving water.' WHERE distance = 1075 * 1.60934;

-- Goal: Camp on small eyot near western shore. Sam and Frodo watch. Gollum appears during Frodo’s watch. Aragorn wakes. Watches until morning (Distance: 1083)
UPDATE goals SET description = 'The Company halted their boats to camp on a small eyot near the western shore, hoping the island would offer better protection than the riverbanks. During the long hours of darkness, Sam and Frodo sat on watch together, and Frodo gasped as he saw two pale, lamp-like eyes observing them from a log drifting in the stream. The creature Gollum had finally been sighted, though he slipped away before he could be caught. Aragorn, roused by the commotion, rose silently to join the watch, standing guard with his sword drawn until the grey dawn finally broke over the Anduin.' WHERE distance = 1083 * 1.60934;

-- Goal: North edge of eastern South Undeep (Distance: 1122)
UPDATE goals SET description = 'The Company guided their small elven-boats carefully through the shoals of the South Undeep, where the Great River broadened and the current ran sluggishly over shifting sands. Aragorn and Boromir laboured constantly to keep the shallow-draft vessels from running aground on the many hidden banks that lurked beneath the grey surface. To their left, the eastern shore stretched out as a treeless, wind-swept flat, offering no cover from the pale, watchful sky. Amidst the silence of the empty lands, the hobbits huddled low in the boats, feeling exposed and small against the vast, drab landscape of the river valley.' WHERE distance = 1122 * 1.60934;

-- Goal: Reach the north edge of western South Undeep (Distance: 1142)
UPDATE goals SET description = 'The Fellowship guided their boats through the winding, shallow waters of the Anduin known as the South Undeep, where the river spread wide between limitless flats of brown land. Aragorn and Boromir found the current sluggish in these reaches, requiring constant effort to keep the vessels moving through the meanders while the hobbits sat silent and huddled against the cold. The low, treeless banks offered no shelter, leaving the company feeling dangerously exposed to whatever eyes might be watching from the eastern shore. A heavy, brooding silence lay over the desolate landscape, broken only by the splash of paddles and the rustle of dry reeds in the wind.' WHERE distance = 1142 * 1.60934;

-- Goal: CAMP during DAY (Feb. 21). Downs on both sides of the river (Distance: 1155)
UPDATE goals SET description = 'The Company drifted silently down the Anduin by night, forced to hide their boats and camp during the grey, cheerless daylight to evade the eyes of their enemies. Upon the banks, the trees had vanished, replaced by bleak downs of stony earth that rose high on either side of the water, shutting out the view of the wider world. The air grew chill as the Fellowship huddled in a fireless camp, listening to the wind hiss over the dry grass of the slopes above. Even Legolas could see little but the pale sky and the grim hills, while Frodo felt the weight of the journey press upon him in this desolate country.' WHERE distance = 1155 * 1.60934;

-- Goal: Reach lowlands between downs and the Emyn Muil (Distance: 1180)
UPDATE goals SET description = 'The Company drifted swiftly down the Great River Anduin, leaving the green downs behind for a bleak and unlovable country of reeds and grey grass. To the east the Brown Lands stretched away, scorched and withered, while ahead the rocky roots of the Emyn Muil began to rise from the flat earth. The air was chill and silent, save for the wind hissing over the water, and the hobbits felt small and exposed in their fragile elven-boats. No birds called in this empty waste, yet an uneasy feeling grew amongst the Fellowship that many eyes were watching them from the barren shores.' WHERE distance = 1180 * 1.60934;

-- Goal: CAMP during DAY (Feb. 22) (Distance: 1205)
UPDATE goals SET description = 'The Company draws their small boats to the western bank as the grey light of morning creeps over the distant hills, forcing them to camp while the sun is high. The River Anduin flows swiftly here, bearing them ever closer to the barren slopes of the Emyn Muil, which now rise forbiddingly on the skyline. Aragorn has commanded that they travel only by night to evade the eyes of Mordor, leaving the weary travellers to sleep uneasily amongst the reeds and low willows. A sense of dread hangs over the makeshift camp, for Sam remains convinced that a dark shape has been trailing their boats like a piece of drifting wood.' WHERE distance = 1205 * 1.60934;

