-- Migration number: 0015 	 2026-01-12T00:00:01.000Z

-- Batch 05: Update goal descriptions for improved accuracy

-- Goal: Hills also appear on the west. The river passes through “low crumbling cliffs, and chimneys with grey weathered stone dark with ivy” (Distance: 1220)
UPDATE goals SET description = 'The Company continued their journey down the Anduin, noticing that the open lands were giving way to distinct rising ground on the western shore. Their boats drifted past low crumbling cliffs and strange natural chimneys of grey weathered stone, which loomed dark with curtains of ivy. This change in the landscape marked the beginning of the stony highlands of the Emyn Muil, closing in on the river from both sides. For Frodo and his companions, the narrowing banks brought a fresh sense of foreboding as the Great River quickened its pace towards the uncertain rapids ahead.' WHERE distance = 1220 * 1.60934;

-- Goal: They reach the higher Emyn Muil (Distance: 1234)
UPDATE goals SET description = 'The grey, treeless slopes of the Emyn Muil now towered high above the water, enclosing the Anduin in a deep rocky trough. The easy meandering of the river ended, replaced by a swift and driving current that carried the small boats rapidly southward between the sheer cliff walls. A brooding silence hung over the canyon, broken only by the sound of the swirling water and the nervous breathing of the travellers as they gazed up at the stony heights.' WHERE distance = 1234 * 1.60934;

-- Goal: Camp on west shore (Feb. 23). Many birds circle during the day. Late in day Legolas sees eagle. Wait to full dark to leave (8:30 p.m.). Go slowly (Distance: 1255)
UPDATE goals SET description = 'The Fellowship hauled their boats onto the western bank, seeking shelter among the grey rocks of the Emyn Muil. An oppressive sense of being watched grew throughout the day, heightened by flocks of birds wheeling overhead. Legolas discerned a single great eagle hunting high in the sky, raising fears that their progress was no longer secret. To avoid detection, the company waited until the moon had set and the canyon was plunged into darkness before daring to continue their slow drift downstream.' WHERE distance = 1255 * 1.60934;

-- Goal: Midnight. Sam hears racing water. North edge of the rapids of Sarn Gebir. ORC ATTACK. Reach western shore. Legolas shoots a Nazgul’s flying beast. Move upstream to a small shallow bay. Huddle in boats rest of the night (Distance: 1267)
UPDATE goals SET description = 'The Company''s journey down the Anduin was abruptly halted by the roaring sound of rushing water, signalling the rapids of Sarn Gebir. Suddenly, arrows whistled from the eastern bank as hidden Orcs launched a fierce ambush under the cover of darkness. Amidst the chaos, a terrifying winged shadow passed overhead, but Legolas, drawing his great bow of Lórien, struck the flying beast down from the sky. Desperate to escape both the rapids and the arrows, the Fellowship fought the current to reach the western shore, finding precarious shelter in a shallow bay where they waited out the night.' WHERE distance = 1267 * 1.60934;

-- Goal: Foggy. Carry boats and packs to foot of rapids – 2 trips. Camp by pool that night (Distance: 1269)
UPDATE goals SET description = 'The following morning, a dense fog shrouded the river, concealing the Fellowship from their enemies on the eastern shore. Realising they could not navigate the perilous rapids of Sarn Gebir, the Company resolved to carry their boats and baggage along an ancient portage-way carved by the men of Gondor. The task was arduous, requiring two burdensome journeys back and forth along the cliff-top path to transport their heavy gear. Exhausted by their labours, they made camp that night by a quiet pool at the foot of the rapids, the roar of the water finally behind them.' WHERE distance = 1269 * 1.60934;

-- Goal: The Argonath. Boats are swept through the narrow gap between (Distance: 1288)
UPDATE goals SET description = 'The Company''s small boats drift beneath the shadow of the Pillars of the Kings, the Argonath. Frodo gazes up in awe at the colossal stone forms of Isildur and Anárion, hewn from the living rock of the precipitous cliffs on either side of the Anduin. These silent sentinels of Númenor, crowned and bearing axes, loom vast and grey against the sky, their stone eyes staring eternally northward. As the current sweeps the craft between the giant feet, the sheer scale of the ancient work fills the travellers with a sense of dread and majesty, marking their entrance into the realm of Gondor.' WHERE distance = 1288 * 1.60934;

-- Goal: Pass out of the chasm into the lake: Nen Hithoel. (ca. 2 p.m.) (Distance: 1290)
UPDATE goals SET description = 'The Fellowship''s boats drifted out from the shadow of the great Pillars into the widening waters of Nen Hithoel. The sheer walls of the chasm fell away, revealing a vast, pale lake encompassed by steep, grey hills that marched southward. Far ahead, the roar of the Falls of Rauros began as a low, ominous vibration in the air, though the water here was still and deep. The Company paddled towards the western shore, their respite beneath the Kings of old replaced by the uncertainty of the lake''s open expanse.' WHERE distance = 1290 * 1.60934;

-- Goal: Reach the lawn of Parth Galen below Amon Hen. “Rauros was calling with a great voice.” Camp there (Distance: 1309)
UPDATE goals SET description = 'The Fellowship camped upon the green lawn of Parth Galen, but the shadow of Mordor had already found them. Here, the unity of the Company was finally shattered as Boromir succumbed to the Ring''s temptation and Orcs swarmed from the forest. In the chaos that followed, Frodo and Sam escaped across the river to the eastern shore, choosing to face the long dark road alone. The remaining companions were left scattered or fallen, and the Fellowship was ended beneath the roar of Rauros.' WHERE distance = 1309 * 1.60934;

-- Goal: The Wetwang curves south (Distance: 1341)
UPDATE goals SET description = 'Alone in the barren wilderness, Frodo and Sam toiled painfully through the sharp, confusing ridges of the Emyn Muil. Looking out from the eastern heights, they saw the Great River flowing away below them, broadening into the fen-lands of the Nindalf, or Wetwang, which curved southward in a haze of reeds and mist. The sheer cliffs and tangled ravines offered no clear path, forcing the hobbits to scramble and slide over the jagged stone with growing desperation. This grim landscape seemed to trap them, presenting a labyrinth of rock between them and the dark road to Mordor.' WHERE distance = 1341 * 1.60934;

-- Goal: Capture Gollum (Distance: 1383)
UPDATE goals SET description = 'After a perilous descent down the sheer cliffs of the Emyn Muil using the elven rope, Frodo and Sam lay in wait for their shadower. The wretched creature Gollum, climbing down the precipice like a spider, was ambushed by the hobbits at the foot of the wall. Though he fought with unexpected strength, the creature was eventually subdued when Frodo drew his sword, Sting, against him. Weeping and grovelling, Gollum swore a binding oath by the Precious to serve the Master of the Ring, becoming their treacherous guide towards the Black Gate.' WHERE distance = 1383 * 1.60934;

-- Goal: Enter the heart of the Dead Marshes (Distance: 1421)
UPDATE goals SET description = 'Guided by Gollum, Frodo and Sam toiled through the reeking fens of the Dead Marshes, a drab and rotting landscape that seemed to stretch endlessly in the cold mist. The air was heavy with the stench of decay, and the only sound was the sucking squelch of their feet in the shifting mud. As night fell, will-o''-the-wisps flickered over the stagnant pools, which Gollum fearfully called the ''candles of corpses.'' Looking down into the dark water, Sam recoiled in horror, for beneath the surface lay the pale, unmoving faces of Men, Elves, and Orcs from battles long past.' WHERE distance = 1421 * 1.60934;

-- Goal: Reach the Desolation of the Morannon (Distance: 1463)
UPDATE goals SET description = 'Frodo, Sam, and Gollum emerged from the festering marshes into a landscape of utter devastation. The Desolation of the Morannon spread before them: a bleak, ash-grey waste where no living thing grew, scarred by countless pits and trenches left by the armies of Mordor. At the far edge of this poisoned plain rose the Black Gate itself, the Morannon, a vast wall of iron stretching between the peaks of the Ephel Dúath and the Mountains of Ash. Watching the ceaseless passage of Orc-hosts and the vigilant Nazgûl circling above, the hobbits realised with sinking hearts that no entrance to Mordor could be forced through those dreadful gates.' WHERE distance = 1463 * 1.60934;

-- Goal: Reach northern edge of Ithilien (Distance: 1499)
UPDATE goals SET description = 'Having despaired of passing the Black Gate, Frodo and Sam followed Gollum southward into a land they had not expected to find so close to Mordor. Ithilien, the garden of Gondor, opened before them as they descended from the ash-choked wastes into groves of fragrant trees and sweet-scented herbs. Birds sang in the thickets, and the hobbits marvelled at the flowers and greenery, a startling contrast to the grey desolation they had left behind. Yet this fair country was not untouched by war; ruins of ancient towers stood among the woods, a reminder that the Shadow in the East had long stretched its hand across this once-peaceful land.' WHERE distance = 1499 * 1.60934;

-- Goal: Led to Henneth Annûn (Distance: 1533)
UPDATE goals SET description = 'Frodo and Sam were discovered by a company of Rangers of Ithilien, Men of Gondor who still patrolled this fallen land behind the enemy''s lines. Their captain, Faramir, younger son of Denethor the Steward, questioned the hobbits keenly about their errand. The Rangers led their small prisoners through winding paths to their hidden refuge: Henneth Annûn, the Window of the Sunset, a cave concealed behind a great waterfall that shimmered with the light of the westering sun. Here Frodo faced a perilous test, for Faramir''s questioning drew ever closer to the secret of the Ring that hung upon his breast.' WHERE distance = 1533 * 1.60934;

-- Goal: End of the forest (Distance: 1577)
UPDATE goals SET description = 'Frodo and Sam, released from the care of Faramir at Henneth Annûn, followed their untrustworthy guide Gollum southward through the dwindling woods of Ithilien. The green boughs and fragrant thickets gradually gave way to scrubland and grey, stony slopes as the land rose toward the mountains of shadow. At the forest''s edge, the hobbits found themselves facing the bleak approaches to the Morgul Vale, where a poisonous darkness seemed to seep into the very air. Ahead lay the ancient road to the Crossroads, and beyond that, the secret path Gollum had promised would lead them into Mordor unseen.' WHERE distance = 1577 * 1.60934;

-- Goal: Frodo is stung by Shelob (Distance: 1612)
UPDATE goals SET description = 'Gollum led Frodo and Sam up the treacherous Stairs of Cirith Ungol, a secret path winding through the mountains that guarded Mordor. At the top of the pass, the creature''s treachery was finally revealed as he lured the hobbits into the lair of Shelob, an ancient and monstrous spider who had dwelt in darkness since before the fall of Sauron''s first master. In the black, stinking tunnel, the great spider attacked without warning, stinging Frodo and leaving him for dead while Sam was held back by Gollum. It was only Sam''s desperate courage, wielding the Phial of Galadriel and Sting, that drove Shelob back into the shadows and gave him a chance to reach his fallen master.' WHERE distance = 1612 * 1.60934;

-- Goal: Stagnant pool of water (Distance: 1651)
UPDATE goals SET description = 'Frodo and Sam, reunited after the horrors of Shelob''s lair and the Tower of Cirith Ungol, now trudged through the slag-heaps and ash-covered wastes of Mordor. Their throats burned with thirst, and the foul air of the Dark Land offered no relief. At last they came upon a pool of stagnant water, its surface dark and unwholesome, but the hobbits had no choice save to drink from it. Though the water tasted of metal and decay, it was the only sustenance to be found in that poisoned realm, a grim reminder of how far they had come from the clear springs of their homeland.' WHERE distance = 1651 * 1.60934;

-- Goal: Out on the plain, drawing near Isenmouthe (Distance: 1698)
UPDATE goals SET description = 'Barely escaping the crushing press of the Orc-host during a collision of companies, Frodo and Sam scuttled into the shadows of the roadside like frightened beetles. The Isenmouthe, a formidable barrier of earthworks and trenches known as the Iron Jaws, loomed directly ahead, serving as the inner gate to the Dark Lord''s sanctuary. Here the sheer scale of Sauron''s war preparations became terrifyingly clear, with thousands of torches and the tramp of iron-shod feet filling the air. The two small figures clambered desperately away from the road and out onto the slag-strewn plain, finding temporary refuge in a deep pit while the noise of the armies rolled by like thunder.' WHERE distance = 1698 * 1.60934;

-- Goal: The Dreadful Nightfall (Distance: 1755)
UPDATE goals SET description = 'The hobbits faced a dreadful nightfall upon the barren plains of Gorgoroth, where the shadows seemed to possess a weight of their own. Frodo Baggins struggled against the crushing burden of the Ring, which grew ever heavier as they drew nearer to the fires of Mount Doom. Their provisions were exhausted, and a terrible thirst gnawed at them, for the land was dry and choked with ash. Amidst this suffocating gloom, Samwise laboured to keep his master moving, though his own heart was heavy with the knowledge that their endurance was nearly at its end.' WHERE distance = 1755 * 1.60934;

-- Goal: Destroy the ring in Mount Doom (Distance: 1779)
UPDATE goals SET description = 'At the very brink of the Crack of Doom, Frodo''s will finally breaks; he refuses the task and claims the Ring as his own. Savage and desperate, Gollum attacks, biting the finger from Frodo''s hand and dancing in mad ecstasy to have his Precious once more. But in his gloating he steps too far, plunging with a shriek into the fiery abyss to be consumed with his prize. The mountain convulses as the Dark Tower crumbles and the skies are rent asunder, whilst the vast Shadow is blown away like sudden smoke. The Quest is achieved, and the long burden is lifted amidst the ruin of Mordor.' WHERE distance = 1779 * 1.60934;

