-- Migration number: 0016 	 2026-01-13T00:00:01.000Z

-- Batch 06: Update goal descriptions for improved accuracy (Return Journey start)

-- Goal: Camp along the road (Distance: 1798)
UPDATE goals SET description = 'The Host of the West sets forth from the Field of Cormallen, making a celebratory journey towards Minas Tirith to prepare for the King''s crowning. Beside the Anduin, the company camps amidst the fragrant woods of Ithilien, where the air is sweet with the scents of spring and victory. Frodo and Sam ride with honour among the captains, no longer burdened by the weight of the Ring or the shadow of the Dark Lord. The travellers rest easily under the stars, savouring the peace that has finally returned to these fair lands.' WHERE distance = 1798 * 1.60934;

-- Goal: Camp near Henneth Annûn (Distance: 1835)
UPDATE goals SET description = 'The returning host halts in the fair woodlands of Ithilien, encamping near the secret refuge known as Henneth Annûn. Above the forbidden pool, the Window on the West looks out from the rock, no longer needing to remain shuttered against the gaze of the Enemy. Frodo and Samwise recall their strange meeting with Faramir within this hidden cave, listening once more to the familiar thunder of the waterfall. It is a moment of quiet reflection for the travellers, standing freely in a place where they once feared for their lives.' WHERE distance = 1835 * 1.60934;

-- Goal: Continue on Southward Road (Distance: 1840)
UPDATE goals SET description = 'The victors travel south from Cormallen, passing through the fragrant woodlands of Ithilien where spring is already in full bloom. Frodo and Sam ride with the Captains of the West, surrounded no longer by enemies but by the fair trees and clear streams of a land healing from the Shadow. As the road winds onwards, the grey hill of Amon Dîn comes into view across the Anduin, standing silent now that the beacons are lit no more. It is a journey of gladness, with the scent of cypress and juniper heavy in the warm air.' WHERE distance = 1840 * 1.60934;

-- Goal: Can see Amon Dîn due west (Distance: 1863)
UPDATE goals SET description = 'The victorious host of the West travels leisurely through the fragrant woods of Ithilien, drawing nearer to the Great River with every step. Far away to the west, the sharp peak of Amon Dîn is clearly visible against the sky, standing as the first of the beacon-hills of Gondor. It no longer signals danger with fire, but now serves as a familiar landmark guiding the company towards the landings of Osgiliath. The peace of the land surrounds the travellers, offering a stark contrast to the darkness they have so recently vanquished.' WHERE distance = 1863 * 1.60934;

-- Goal: Reach landings of Osgiliath (Distance: 1886)
UPDATE goals SET description = 'The victorious Host of the West sails down the broad waters of the Anduin, arriving at the battered stone landings of Osgiliath. Broken arches and toppled masonry bear witness to the fierce battles fought within the Citadel of the Stars, yet the river now carries the King returning to his realm. The company disembarks amidst the grey ruins where the fleet has anchored, preparing to cross the river towards the Pelennor Fields. Ahead, the white tower of Minas Tirith gleams in the sunlight, awaiting the arrival of its lord.' WHERE distance = 1886 * 1.60934;

-- Goal: Reach the Gates of Minas Tirith (Distance: 1899)
UPDATE goals SET description = 'Aragorn is crowned King Elessar outside the Gates of Minas Tirith, marking the beginning of a new age for Gondor and Middle-earth. The Fellowship is joyously reunited in the company of the King, who enters the City amidst the cheering of the multitude and the music of trumpets. The White Tree is found again, and the days of the King are blessed with peace and renewal.' WHERE distance = 1899 * 1.60934;

-- Goal: Camp by road north of the Drúadan Forest (Distance: 1949)
UPDATE goals SET description = 'The solemn procession, including the Fellowship and the knights of Rohan, escorts the wain bearing King Théoden towards Edoras. As the travellers pass the northern borders of the Drúadan Forest, the drums of the Wild Men remain silent, and the ancient trees keep their counsel. King Elessar halts the company here to proclaim that the Grey Wood shall belong to Ghân-buri-Ghân and his people forever, forbidding any man to enter without their leave. The encampment settles for the night by the roadside, finding peace where once there was only the desperate haste of war.' WHERE distance = 1949 * 1.60934;

-- Goal: Pass the beacon on Nardol, the “Fire Hill” (Distance: 2000)
UPDATE goals SET description = 'The funeral procession continues its solemn journey westward, winding along the road beneath the white peaks of the Ered Nimrais. High on their left rises the steep abrupt mass of Nardol, the Fire-hill, standing guard over the ancient Drúadan Forest where the Wild Men dwell. The beacons that once flared with urgent warning to summon the Rohirrim now stand cold and unlit against the bright summer sky. The great wain bearing King Théoden rolls past in peace, returning the Lord of the Mark to his final rest in Edoras.' WHERE distance = 2000 * 1.60934;

-- Goal: The beacon hill of Minrimmon is on the left (Distance: 2051)
UPDATE goals SET description = 'The funeral host of King Théoden makes its slow way westward through Anórien, following the road beneath the northern slopes of the White Mountains. The steep hill of Minrimmon rises to the left, standing silent where warning fires had so recently burned against the night. This beacon, once a desperate call for aid, now serves only as a milestone for the company returning to Rohan. The travellers pass beneath its shadow in peace, bearing the body of Théoden King back to the land of the horse-lords.' WHERE distance = 2051 * 1.60934;

-- Goal: The beacon tower of Calenhad stands on a foothill of Calenhad peak (Distance: 2080)
UPDATE goals SET description = 'The company travels slowly westward with the wain of King Théoden, passing the beacon hills that once signalled the desperate need of Gondor. The tower of Calenhad stands silent on its foothill, its wood unburnt and its watchers at rest in the newfound peace. No longer driving their horses in haste, the travellers ride solemnly beneath the peak, honouring the alliance that saved the West.' WHERE distance = 2080 * 1.60934;

-- Goal: North of the road, is the Entwash (Distance: 2166)
UPDATE goals SET description = 'The company travels westward from the woods of the Halifirien, crossing the Mering Stream to enter the open lands of the Rohirrim. North of the road, the Entwash spreads into wide marshes, separating the returning heroes from the wilder fields beyond as it flows to join the Anduin. The travellers proceed with solemn pageantry, bearing the body of King Théoden back to Edoras, surrounded by the Riders of the Mark and the knights of Gondor.' WHERE distance = 2166 * 1.60934;

-- Goal: Leave the Folde (Distance: 2206)
UPDATE goals SET description = 'The great funeral procession bears the body of King Théoden across the green lands of the Folde, the heart of the Mark. A host of the Riders of Rohan guards the golden wain, while the company travels in solemn silence towards the rising slopes of the White Mountains. Ahead, the swift waters of the Snowbourn flow from the Harrowdale, marking the approach to Edoras and the Golden Hall. Here, amidst the simbelmynë, the King will finally come to rest in the hallowed barrows of his house.' WHERE distance = 2206 * 1.60934;

-- Goal: Ford the Snowbourn (Distance: 2260)
UPDATE goals SET description = 'The great company reaches the banks of the Snowbourn, where the cold, white waters rush past the foot of the green mound of Edoras. Here the funeral procession pauses, and the Riders of the Mark come forth to greet their returned King, bearing him with reverence towards the Golden Hall of Meduseld. Merry gazes up at the familiar courts where he swore service to Théoden, his heart heavy with the sorrow of the long journey''s end. This crossing marks the beginning of the solemn rites, as the voices of the Rohirrim rise in a lament that mingles with the roar of the river.' WHERE distance = 2260 * 1.60934;

-- Goal: Cross a small stream (Distance: 2316)
UPDATE goals SET description = 'The company rides across the green expanse of the Westfold, leaving the burial mounds of Edoras behind. A swift stream cuts through the plain, fed by the high snows of the White Mountains that loom to the south. The travellers guide their horses through the chill water, the splashing hooves breaking the quiet of the afternoon. Though the war is won, the road home for the hobbits remains long, winding first towards the stone walls of Helm''s Deep.' WHERE distance = 2316 * 1.60934;

-- Goal: Cross another small stream (Distance: 2346)
UPDATE goals SET description = 'The company travels through the Deeping Coomb, crossing a swift tributary that tumbles down from the high peaks of the White Mountains. Ahead lies the fortress of Helm''s Deep, standing quiet against the grey stone, no longer besieged by the armies of Saruman. Legolas and Gimli ride together, their conversation turning to the Glittering Caves which they have promised to visit upon their return. The water around the horses'' hooves is crystal clear, washing away the dark memories of the battle that had once raged in this valley.' WHERE distance = 2346 * 1.60934;

-- Goal: Reach Helm''s Deep (Distance: 2378)
UPDATE goals SET description = 'The company halts at Helm''s Deep, resting for two days at the Hornburg where the great battle was formerly won. Legolas fulfils his bargain with Gimli by entering the Glittering Caves of Aglarond, and he returns silent with wonder at the stone-gardens hidden beneath the earth. The Elf admits that Gimli''s words were true, acknowledging that the subterranean beauty surpasses even the fair woods of Lothlórien. Thus the travellers depart the Deeping-coomb, riding northwards towards the Fords of Isen.' WHERE distance = 2378 * 1.60934;

-- Goal: Treegarth of Orthanc, Isengard is no more (Distance: 2434)
UPDATE goals SET description = 'The company finds Isengard transformed into the Treegarth of Orthanc, where the Ents have planted a thriving garden to heal the scars of Saruman''s industry. Treebeard welcomes the travellers amidst the young trees and bubbling orchards that now surround the lonely black tower. He reveals that Saruman has been released from his captivity, having used his voice to persuade the Ents that he is no longer a threat. The hobbits feel a chill at the news of the wizard''s escape, realising that even a defeated enemy may still harbour malice in the wild.' WHERE distance = 2434 * 1.60934;

-- Goal: Camp, still in the Gap of Rohan (Distance: 2479)
UPDATE goals SET description = 'The company rode northwards from the Treegarth, passing through the Gap of Rohan where the land was recovering its green life after the works of Saruman. To the east the Misty Mountains came to an end in steep slopes, while far away the White Mountains faded into the rich plains of Calenardhon. The travellers camp under the stars, feeling the fresh wind of the gap, though the empty lands of the north now lay before them. Gandalf rode with them, silent and deep in thought, as if sensing that their business with the fallen wizard of Isengard was not yet wholly concluded.' WHERE distance = 2479 * 1.60934;

-- Goal: Camp by a small stream (Distance: 2509)
UPDATE goals SET description = 'The travellers ride away from Isengard, turning their backs on the ruined fortress to follow the road near the Gap of Rohan. As they make for the Drift-road, they overtake a ragged old man and his servant, recognising the fallen Saruman and Wormtongue in their misery. The encounter leaves a shadow on the afternoon, but they press on to pitch camp beside a small stream in the fading light. The sound of clear water flowing through the green lands of Dunland helps to cleanse the memory of the wizard''s spiteful words.' WHERE distance = 2509 * 1.60934;

-- Goal: Camp at base of an out-thrust hill of Methedras (Distance: 2539)
UPDATE goals SET description = 'The company continues their northward trek along the feet of the Misty Mountains, where the great horn of Methedras looms high above the roots of Isengard. At the base of a large out-thrust hill beneath this southernmost peak, the travellers halt to make camp for the night. Galadriel and Celeborn remain with the group, their presence adding a quiet grace to the wild lands near the Gap of Rohan. The hobbits and their companions enjoy a peaceful evening in the shadow of the mountains, though the recent encounter with the beggar Saruman lingers in their thoughts.' WHERE distance = 2539 * 1.60934;
