-- Migration number: 0017 	 2026-01-13T00:00:01.000Z

-- Batch 07: Update goal descriptions for improved accuracy (Return Journey to Rivendell and beyond)

-- Goal: Reach the remains of the roadway to Tharbad (Distance: 2569)
UPDATE goals SET description = 'The returning company traces the route of the Old South Road, which has decayed from a royal highway into a mere track through the wilderness. As the travellers cross the wet flats north of the Gap of Rohan, they find only the crumbling remains of causeways and long green embankments to mark the ancient engineering. They ride steadily towards the crossing at Tharbad, with the Misty Mountains rising to the east and the empty lands of Eregion awaiting them. Though the stones are gone, the shadow of the road still leads them away from Isengard and back towards the sanctuary of Rivendell.' WHERE distance = 2569 * 1.60934;

-- Goal: Stop at a small stream (Distance: 2599)
UPDATE goals SET description = 'The company travels northward through the quiet lands between the Misty Mountains and the expanse of the Enedwaith, finding the ancient stones of the roadway mostly hidden by long grass. Beside a small, clear stream that cuts across their path, the travellers halt to water their ponies and prepare a midday meal under the open grey sky. Frodo and his companions enjoy the peaceful stillness of the wild country, a stark contrast to the dark tumult of the war they have left behind. Although the road is lonely, the Fellowship finds comfort in the familiar routines of travel as they draw closer to the borders of Eregion.' WHERE distance = 2599 * 1.60934;

-- Goal: Enter Northern Dunland (Distance: 2629)
UPDATE goals SET description = 'The travellers press on through Northern Dunland, keeping the high slopes of the Misty Mountains to their right hand. Having left the old beggar Saruman muttering by the wayside, the company finds the air fresher and the road open before them. They begin to draw away from the steep foothills, riding over wide, grassy swells of land that show little sign of recent war. It is a quiet leg of the journey, marked only by the steady rhythm of hooves and the grey peaks watching silently from the east.' WHERE distance = 2629 * 1.60934;

-- Goal: Draw farther and farther from the mountains and foothills (Distance: 2674)
UPDATE goals SET description = 'The travellers follow the road through Dunland as it bends westward, carrying them steadily away from the dark roots of the Misty Mountains. As the rocky foothills recede into the grey distance, the landscape flattens, guiding the company towards the low-lying wetlands that wait to the north. The ancient marshes of the Swanfleet lie ahead, marking the boundary where the wild lands will soon give way to the ruins of Eregion on their homeward journey.' WHERE distance = 2674 * 1.60934;

-- Goal: Marshes of the Swanfleet lie to the north (Distance: 2719)
UPDATE goals SET description = 'The company rides northwards through the deserted lands of Eregion, leaving the Misty Mountains on their right hand. To their left, the Marshes of the Swanfleet spread out in a haze, marking the junction where the Glanduin meets the loud-flowing Hoarwell. These fenlands are a sombre sight, echoing with the cries of river-birds, but offering no easy passage for the travellers. The hobbits keep to the firmer ground east of the wetlands, their hearts lightening as each mile brings them closer to the Last Homely House.' WHERE distance = 2719 * 1.60934;

-- Goal: Can see mists above the fens of the Swanfleet delta (Distance: 2759)
UPDATE goals SET description = 'The returning travellers look out over the confluence of the Glanduin and the Greyflood, watching the pale mists coil above the fens of the Swanfleet. Although the Nîn-in-Eilph seems quiet now, the hobbits recall tales of the great hosts of swans that once inhabited this vast, watery delta. The company rides along the borders of the marshland, their path taking them steadily closer to the ancient realm of Eregion and the road to Rivendell. The grey haze over the pools obscures the horizon, serving as a bleak yet peaceful marker on their homeward journey.' WHERE distance = 2759 * 1.60934;

-- Goal: Reach the ruins of Ost-en-Edhil (Distance: 2809)
UPDATE goals SET description = 'The Company walks amidst the crumbled foundations of Ost-en-Edhil, where the Gwaith-i-Mírdain once crafted rings of power in the shadow of the Misty Mountains. Legolas pauses to listen to the stones, hearing them lament the fair folk who vanished from Eregion long ago. The eerie silence of the land unsettles the other travellers, for only the cry of birds breaks the stillness of this desolate country. As they continue east along the old road, the three peaks of Moria rise like jagged teeth against the grey sky.' WHERE distance = 2809 * 1.60934;

-- Goal: Continue east on Moria-road. Mountains of Moria rise ahead (Distance: 2839)
UPDATE goals SET description = 'The company follows the ancient stones of the Moria-road through the desolate yet fair lands of Hollin, drawing ever closer to the roots of the Misty Mountains. To the east, the three great peaks of the Mountains of Moria—Caradhras, Celebdil, and Fanuidhol—pierce the sky, their snowy caps gleaming innocently in the sunlight. This sight stirs dark memories for the hobbits, who recall the bitter snows of the Redhorn Pass and the terror of the wargs that once hunted them in this very wild. Yet now the air is peaceful, and the empty land holds no echo of the Shadow, offering only the quiet solitude of Eregion.' WHERE distance = 2839 * 1.60934;

-- Goal: Reach the hill where the Fellowship had sheltered from the Warg attack (Distance: 2874)
UPDATE goals SET description = 'The travellers identify the hillock crowned with a circle of stones where the Fellowship was once besieged by Wargs. Scorch marks still stain the rocks from the magical fire Gandalf wielded to drive back the wolves during that terrifying night. Standing in the quiet daylight, the hobbits marvel at the blackened evidence of their past struggles, measuring how far they have come since that winter evening. They leave the silent hill behind, riding through Eregion with hearts lighter than on their outward quest.' WHERE distance = 2874 * 1.60934;

-- Goal: Open country. Gentle slopes, easier for the ponies (Distance: 2909)
UPDATE goals SET description = 'The company traverses the open country of Hollin, finding the gentle slopes far easier for the ponies than during the dark days of the quest. Frodo and his friends ride without fear of the wargs that once besieged the Fellowship upon the nearby hill, for the land is now silent and peaceful under the sun. The travellers retrace their path through the ancient realm of Eregion, making good speed northwards towards the hidden sanctuary of Rivendell. Galadriel and Celeborn ride with the hobbits, their bright presence banishing the shadows that once haunted this rugged wilderness.' WHERE distance = 2909 * 1.60934;

-- Goal: Camp atop Hollin Ridge among the large smooth towering rocks (Distance: 2959)
UPDATE goals SET description = 'The travellers establish their camp atop a prominent ridge in Hollin, sheltered by a cluster of large, smooth rocks that tower against the starry sky. Frodo and his companions find the silence of Eregion peaceful now, a stark contrast to the dread they felt years ago when fleeing towards the mountains. The ponies graze contentedly around the base of the stone pillars while Gandalf sits in quiet contemplation of the road behind them. With the Shadow defeated, the empty lands hold no terror, allowing the company to rest deeply before the final leg of their journey to Rivendell.' WHERE distance = 2959 * 1.60934;

-- Goal: Descend a slope to a small stream valley (Distance: 3015)
UPDATE goals SET description = 'Gandalf leads the company down from the rocky heights of Hollin, guiding them along a steep slope into a secluded valley cut by a small stream. The hobbits find the landscape of Eregion strangely quiet, stripped of the ancient malice that had dogged their footsteps during the quest''s beginning. Grey water swirls around mossy stones as the travellers cross the valley floor, the silence broken only by the clatter of pony hooves and the rustle of dry leaves. This peaceful hollow offers a brief respite before their path turns northeast towards the Ford of Bruinen.' WHERE distance = 3015 * 1.60934;

-- Goal: Climb northeast up a slope. In the west, the marsh ends (Distance: 3049)
UPDATE goals SET description = 'The company climbs northeast up a steep slope, seeing the end of the marshland in the west as the land rises towards the distant red horn of Caradhras. To their left, the Bruinen cuts deeply through the stone, its roar a constant companion in the silence of the high country. Gandalf rides with the hobbits over the rough terrain, accompanied by Elrond and Galadriel, while the peaks of the Misty Mountains loom ahead. There is no longer any need to hide or keep watch, for the land is empty and peaceful, cleansed of the shadows that once hunted them here.' WHERE distance = 3049 * 1.60934;

-- Goal: To the west the Loudwater/Bruinen now runs in a deep valley (Distance: 3071)
UPDATE goals SET description = 'The returning company treks along the highlands where the ground falls away sharply to the west, revealing the Loudwater flowing in a deep, carved valley. This swift river, the Bruinen, rushes through the ravine towards the Ford, marking the final barrier before the sanctuary of Rivendell. Frodo and his companions look down upon the grey waters that once rose to defend them against the Ringwraiths, though now the stream runs clear and peaceful. The sight of the deep valley brings hope to the weary hobbits, for they know the Hidden Valley lies just beyond the river''s edge.' WHERE distance = 3071 * 1.60934;

-- Goal: Turn slightly west of north (Distance: 3099)
UPDATE goals SET description = 'The company adjusts their course on the high moors, turning slightly west of north as they navigate the pathless lands above the deep valley of the Bruinen. Gandalf guides the returning travellers away from the cliff''s edge, seeking the concealed entrance that leads down to the Last Homely House. The memory of their desperate flight to the Ford nearly a year ago fades in the bright sunlight, replaced by the anticipation of a peaceful welcome in Elrond''s halls. Amidst the heather and weather-stained rocks, the hobbits look forward to the sudden, breathtaking reveal of the hidden sanctuary.' WHERE distance = 3099 * 1.60934;

-- Goal: Reach the Last Homely House (Distance: 3127)
UPDATE goals SET description = 'The travellers come at last to the brink of the deep valley, seeing the lights of the Last Homely House glowing far below in the dusk. Frodo and his companions are reunited with Bilbo Baggins, who sits surrounded by a clutter of papers and pencils, eager to hear the full tale of their quest. They linger in the peace of Rivendell for a fortnight, resting and celebrating Bilbo''s one hundred and twenty-ninth birthday before turning their thoughts towards the Shire.' WHERE distance = 3127 * 1.60934;

-- Goal: Reach the Ford (Distance: 3135)
UPDATE goals SET description = 'The company rides down the steep path from Rivendell and crosses the Ford of Bruinen, finding the waters shallow and clear. Frodo and his companions pause on the western bank, recalling the terrifying flood that once swept the Ringwraiths away at this very spot. With the Last Homely House now hidden behind the hills, the travellers set their faces towards the Bree-land, carrying memories of healing and rest to warm them on the road ahead.' WHERE distance = 3135 * 1.60934;

-- Goal: Bruinen turns more to the south (Distance: 3156)
UPDATE goals SET description = 'The company rides west from the Ford, reaching the point where the Road bears right to climb into the hills while the river Bruinen turns sharply to the south. Far below in a deep ravine, the water foams over rocks, leaving the travellers to follow the track upwards away from the valley. Gandalf leads the hobbits at a steady pace, retracing the steps of their former flight but now without the terror of the Black Riders. The wild lands of the Trollshaws rise before them, silent and empty in the autumn air.' WHERE distance = 3156 * 1.60934;

-- Goal: Reach pathway to Stone Trolls (Distance: 3185)
UPDATE goals SET description = 'The company turns aside from the road into a thicket of hazel and birch, led by Gandalf towards a relic of an older adventure. In a quiet glade, they find the three stone trolls that Bilbo once encountered, now standing silent and overgrown with age. Sam gazes at the petrified figures with awe, recognising the subjects of the song he so often recited in the Shire. The afternoon sun warms the moss-covered forms of Tom, Bert, and William, who remain forever frozen in their quarrel by the breaking of a dawn long passed.' WHERE distance = 3185 * 1.60934;

-- Goal: Cross The Last Bridge (Distance: 3199)
UPDATE goals SET description = 'The travellers cross the Last Bridge, where the road spans the rushing waters of the Mitheithel under its three stone arches. Memories of their flight to the Ford with Strider return to them, though the terror of the Black Riders has long since vanished from these lands. On their outward journey, they had found a beryl stored here by Glorfindel as a sign of hope, but now the bridge simply marks another league towards home. The river flows grey and cold beneath them as they leave the Trollshaws behind for the open country.' WHERE distance = 3199 * 1.60934;
