-- Migration number: 0018 	 2026-01-13T01:00:00.000Z

-- Batch 08: Update goal descriptions for improved accuracy (Return Journey to Weathertop)

-- Goal: Open country (Distance: 3219)
UPDATE goals SET description = 'The travellers rode on into the open country west of the River Hoarwell, where the dread of their earlier flight was now replaced by the quiet peace of late autumn. Gandalf and the hobbits camped under the starlit sky, entirely free from the terror of Black Riders that had once haunted these very lands. Though the Weather Hills were not yet within view, the air held a crisp promise of the familiar, and the road stretched out comfortably before them. No longer hunted, the company moved at a leisurely pace, savouring the simple joy of returning home through the wild.' WHERE distance = 3219 * 1.60934;

-- Goal: Begin to see tops of the Weather Hills (Distance: 3234)
UPDATE goals SET description = 'The travellers continued westward along the Great Road, leaving the Hoarwell far behind them as the land began to rise. Ahead, the grey summits of the Weather Hills finally broke the horizon, appearing as distant, jagged teeth against the pale sky. Frodo and his friends looked upon the range with changed eyes, for while the hills still held memories of the Ringwraiths'' attack, they now served as a familiar landmark guiding them back to Bree. The sight of the hilltops offered a tangible sign that the wild loneliness of the Trollshaws was ending and the borders of the settled lands were drawing near.' WHERE distance = 3234 * 1.60934;

-- Goal: Weather Hills slowly rise on the horizon (Distance: 3256)
UPDATE goals SET description = 'The returning company travelled openly along the Great East Road, leaving the wooded Trollshaws and the Last Bridge far behind. Slowly, the Weather Hills began to rise on the western horizon, their grey ridges standing stark against the pale sky. Frodo and his companions gazed towards the approaching heights, recalling the terror of their previous crossing with a quiet solemnity rather than fear. No longer hunted fugitives hiding in the wild, the travellers rode at ease towards the ancient landmark, though the memory of the Black Riders still lingered in this lonely place.' WHERE distance = 3256 * 1.60934;

-- Goal: Weathertop becomes visible straight ahead (Distance: 3279)
UPDATE goals SET description = 'Frodo and his friends rode westwards under a clear autumn sky as the grey line of the Weather Hills began to rise from the plains ahead. The tall, flattened cone of Weathertop soon became visible straight before them, evoking dark memories for the Ring-bearer of the Witch-king''s knife and the terror of the Nazgûl. Though the ancient watchtower of Amon Sûl still stood grim and stark, the land was now purged of the Shadow that had once hunted them there. It remained only as a silent landmark on their homeward road, marking the distance they had travelled since those desperate early days.' WHERE distance = 3279 * 1.60934;

-- Goal: Land rises slowly toward Hills (Distance: 3294)
UPDATE goals SET description = 'The company rode westward along the Great East Road as the ground began to lift steadily towards the barrier of the Weather Hills. Gandalf and the hobbits ascended the long slopes, watching the landscape become more rugged and broken as they left the flat lands behind. Ahead, the grey ridges stood like a wall across their path, signaling that the ancient watchtower of Amon Sûl was close at hand. The journey here was peaceful, a stark contrast to the peril they had faced when last they traversed these wilds.' WHERE distance = 3294 * 1.60934;

-- Goal: Weathertop immediately north of road (Distance: 3324)
UPDATE goals SET description = 'The returning company rode beneath the shadow of Weathertop as it rose starkly to the north of the Great East Road. Frodo gazed up at the ruined summit of Amon Sûl, recalling the night of terror when the Witch-king''s blade pierced his shoulder in the dell below. Now the ancient watchtower stood silent and empty, no longer harbouring the Nine or their malice. The travellers passed the landmark in peace, contrasting this quiet afternoon with the desperate fear of their outward journey, before the road led them down towards the lowlands.' WHERE distance = 3324 * 1.60934;

-- Goal: Southeast edge of the Midgewater Marshes (Distance: 3359)
UPDATE goals SET description = 'The returning travellers press westward along the Great East Road, keeping a steady pace on the firm surface. Frodo and his friends look towards the north, observing the treacherous expanses of the Midgewater Marshes from a safe distance, relieved to not be struggling through the mire and biting insects this time. Unlike their hurried and secretive flight with Strider months ago, the company now rides openly with Gandalf, bypassing the fen-mist and stagnant pools that once plagued their step. The road stretches on towards Bree, offering a far easier passage than the pathless wilds they had previously been forced to traverse in fear.' WHERE distance = 3359 * 1.60934;

-- Goal: Camp. Marshes farther north from the road (Distance: 3391)
UPDATE goals SET description = 'The company establishes their camp on the firm ground near the Great East Road, looking northwards towards the dreary expanse of the Midgewater Marshes. Frodo and Sam remember all too well the last time they faced this landscape, driven into the fly-infested bogs by the fear of Black Riders, but now they travel with Gandalf in safety. Instead of a desperate flight through mud and brambles, the hobbits enjoy a quiet evening, contrasting their current peace with the misery of their outward journey. The grey fens that once seemed an interminable obstacle are now merely a feature of the passing landscape as they make their way homeward.' WHERE distance = 3391 * 1.60934;

-- Goal: Camp in stables of The Forsaken Inn (Distance: 3423)
UPDATE goals SET description = 'The travellers halt for the evening at the Forsaken Inn, a dreary and dilapidated establishment standing as a lonely marker just east of the Bree-land. Choosing to avoid the gloom of the main building, the company establishes their camp within the relative shelter of the stables. Although the setting is bleak, spirits remain high with the knowledge that the friendly lights of the Prancing Pony are merely a day''s march to the west. This rough accommodation serves as the final boundary between the long, perilous road behind them and the welcoming civilisation just ahead.' WHERE distance = 3423 * 1.60934;

-- Goal: Bree: arrive at The Prancing Pony (Distance: 3439)
UPDATE goals SET description = 'The company rides back into Bree and halts at The Prancing Pony, where Barliman Butterbur stares at them as if seeing ghosts. The worthy landlord had long since given the hobbits up for dead, and he frankly admits his astonishment at seeing them return as lordly figures, far changed from the frightened runaways he once sheltered. As they sit by the fire once more, the travellers listen to Butterbur''s anxious tales of trouble in the North and ruffians gathering on the borders. It becomes clear that while the great darkness has fallen in the South, smaller evils still linger to threaten the peace of the Shire.' WHERE distance = 3439 * 1.60934;

-- Goal: The Old Forest begins to the south (Distance: 3455)
UPDATE goals SET description = 'The travellers rode westward along the East Road, leaving the comfort of Bree behind. To their left, the land fell away into the dark, tangled canopy of the Old Forest, visible once more against the horizon. It was here that Gandalf chose to part ways with the company, turning his horse south to visit Tom Bombadil in his mossy house. Frodo and his companions continued alone towards the Brandywine Bridge, no longer daunted by the ancient trees that had once seemed so threatening.' WHERE distance = 3455 * 1.60934;

-- Goal: Reach the Brandywine Bridge (Distance: 3479)
UPDATE goals SET description = 'The four travellers rode down the Causeway to the Brandywine Bridge, only to find their way blocked by a great gate spiked with iron. Where the bridge had once stood open to all, now new guardhouses loomed in the twilight, and nervous Shirrifs emerged to enforce the Chief''s harsh rules. Frodo and his companions, their mail clanking softly beneath their cloaks, gazed upon these grim changes with a heavy realisation. The dark shadow they had fought in the East had cast a long gloom even over the borders of the Shire.' WHERE distance = 3479 * 1.60934;

-- Goal: Frogmorton (Distance: 3501)
UPDATE goals SET description = 'The four travellers arrived at the water-surrounded village of Frogmorton, only to find the road barred by a large troop of Shirriffs armed with staves. Instead of a warm welcome at The Floating Log, the companions were officiously halted and declared under arrest by order of the Chief at Bag End. Merry and Pippin treated the situation with amused contempt, their mail-clad stature towering over the flustered hobbit-guards who tried to enforce the new Rules. It was a stark sign of the troubles that had taken root in the Shire, turning a once-friendly hamlet into a place of suspicion and closed doors.' WHERE distance = 3501 * 1.60934;

-- Goal: Reach Bag End (Distance: 3524)
UPDATE goals SET description = 'Frodo and his companions ascend the Hill to stand once more before the round green door of Bag End, finding the comfortable smial sadly altered by its occupation as Sharkey''s headquarters. Upon the very doorstep where the quest began, the hobbits witness the end of Saruman and Grima Wormtongue, watching as the wizard''s spirit dissolves like grey mist in a wind from the West. The scouring is complete, and though the Shire has been marred, the travellers can finally set down their packs in the place they once left so long ago. With the shadow finally lifted, Samwise turns his thoughts to the gift of Galadriel and the healing of the wounded land.' WHERE distance = 3524 * 1.60934;

-- Goal: Reach Stock Road (Distance: 3538)
UPDATE goals SET description = 'Frodo and Sam rode quietly from Hobbiton, guiding their ponies down to the Stock Road to begin the journey that would lead them to the sea. The travellers passed through the familiar landscapes of the Eastfarthing, retracing the path of their initial flight, though now the air was free of the fear of Black Riders. This road guided them towards the Woody End, where the Last Riding of the Keepers awaited their arrival in the twilight. It was a solemn departure, carrying the Ring-bearer away from the home he had saved but could no longer truly inhabit.' WHERE distance = 3538 * 1.60934;

-- Goal: Reach the point where the road splits (Distance: 3561)
UPDATE goals SET description = 'The hobbits halted their ponies at the junction where the lane from the Woody End met the Great East Road. It was here that the Last Riding of the Keepers emerged from the twilight, with Elrond and Galadriel bearing the Three Rings of Power openly on their fingers. Riding beside the Elven-lords was an elderly Bilbo Baggins, who woke from a nap to cheerfully announce his readiness for this final adventure. The reunited company turned their faces westward, travelling in silence through the cooling air as they began the long road to the Sea.' WHERE distance = 3561 * 1.60934;

-- Goal: Camp in the open lands (Distance: 3614)
UPDATE goals SET description = 'The Last Riding of the Keepers halts for the night under the wide canopy of the Shire sky, far from the busy lanes of the villages. Frodo and Sam rest alongside the glittering company of Elves, the air around them filled with the soft, sad music of the ending age. This open encampment offers a final, peaceful embrace of the land they love, untainted by the shadow that once hunted them across these very fields. Here, amidst the scent of dew and grass, the hobbits share a quiet meal, knowing that the road ahead leads only to the Sea and the parting of ways.' WHERE distance = 3614 * 1.60934;

-- Goal: Pass south of Tuckburrow (Distance: 3626)
UPDATE goals SET description = 'The travellers make their way westward through the Shire, passing near the Green Hill Country and skirting the rolling boundaries of the Tookland. As they ride south of Tuckburrow, the ancestral seat of the Thains where Peregrin''s family dwells, the land appears lush and peaceful, fully recovered from the ruin of Sharkey''s rule. Yet Frodo moves through these beloved fields with a quiet detachment, knowing that for him, the saving of the Shire has not brought personal peace. Their journey carries them steadily away from the heart of the hobbit-lands towards the White Downs and the final road to the Sea.' WHERE distance = 3626 * 1.60934;

-- Goal: Beyond the Downs are grassy lowlands, almost uninhabited (Distance: 3639)
UPDATE goals SET description = 'The company rode slowly through the autumn-clad Westfarthing, where the trees were kindled with gold and the air was still and sweet. Frodo rode beside Bilbo and the Elven-lords, his gaze often turning to the western horizon where the sun was sinking into a mist of cloud. They passed few dwellings in these western reaches, and the familiar green hills of the Shire began to give way to the rising slopes that heralded the edge of the little land the hobbits called home.' WHERE distance = 3639 * 1.60934;

-- Goal: Reach the crest of the Far Downs (Distance: 3669)
UPDATE goals SET description = 'Frodo and his companions rode steadily westward, ascending until they attained the high crest of the Far Downs. Before the travellers lay a wide expanse of grassy lowlands, silent and nearly uninhabited, rolling away towards the distant sea. Upon the western horizon, the ancient white towers of the Tower Hills gleamed pale against the sky, marking the boundary of the Elven lands. The air here tasted faintly of salt, carrying the first breath of the Sea to meet the Ring-bearer on his final journey.' WHERE distance = 3669 * 1.60934;
