-- Migration number: 0019    2026-01-13T01:00:00.000Z

-- Batch 09: Update goal descriptions for improved accuracy

-- Goal: Can see the Tower Hills on the western horizon (Distance: 3684)
UPDATE goals SET description = 'The company crosses the boundary of the Shire and sees the three White Towers of Emyn Beraid rising starkly against the evening sky on the western horizon. These ancient hills hold the tallest tower, Elostirion, where the palantír commanded by the Elves looks only across the Sundering Seas towards the Undying Lands. A scent of salt hangs in the air, drifting inland from the Great Sea, signalling to Frodo and Sam that their long road is finally drawing to its end.' WHERE distance = 3684 * 1.60934;

-- Goal: Land begins to rise toward the Tower Hills (Distance: 3704)
UPDATE goals SET description = 'The hobbits ride westward through the Westfarthing, where the gentle fields eventually begin to swell and lift towards the sky as the land rises. Ahead on the horizon, the three White Towers of the Emyn Beraid stand tall and grey, ancient sentinels guarding the path to the Sea. Frodo''s gaze remains fixed upon the climbing road, drawn inexorably toward the high ridges that mark the very edge of the Shire. Though the autumn sun is bright, a poignant silence accompanies the group, for the rising ground leads them ever closer to the Grey Havens and the end of the Fellowship.' WHERE distance = 3704 * 1.60934;

-- Goal: Reach the Great East Road (Distance: 3724)
UPDATE goals SET description = 'Frodo and Sam guided their ponies away from the comforts of the Shire and onto the ancient stones of the Great East Road. The highway stretched westward, climbing steadily through the White Downs towards the distant, gleaming shapes of the Tower Hills. A quiet solemnity hung over the travellers, for they knew this road led not to new adventures, but to the final parting at the Grey Havens. Steps that had once hastened towards danger now moved with a deliberate slowness towards the sea.' WHERE distance = 3724 * 1.60934;

-- Goal: Road reaches the Towers at the crest of the hills (Distance: 3744)
UPDATE goals SET description = 'The travellers follow the Great East Road as it climbs the steep slopes of the Tower Hills, where three ancient white towers pierce the sky. Built in the dawn of the North-kingdom, these tall spires, of which Elostirion is the mightiest, stand as silent guardians over the western borders of the Shire. Frodo and Sam ride in the company of the Ring-bearers, passing the immemorial stones that have long gazed out towards the Sea. As they reach the crest, the land falls away before them, and the scent of salt air drifts up from the distant Gulf of Lhûn.' WHERE distance = 3744 * 1.60934;

-- Goal: Land drops gently down toward the Gulf (Distance: 3764)
UPDATE goals SET description = 'The riders pass the ancient White Towers on the Tower Hills, leaving the Shire''s western borders behind them. As the land drops gently down toward the Gulf of Lhûn, the salt air meets them, carrying the mournful cries of sea-birds. Frodo and the bearers of the Three Rings approach the long grey inlet where Círdan the Shipwright waits at the quay. The journey that began with a single step from Bag End now winds its way to the very edge of Middle-earth, where a white ship sits ready to sail into the West.' WHERE distance = 3764 * 1.60934;

-- Goal: Say farewell. The White Ship sails Into the West (Distance: 3784)
UPDATE goals SET description = 'The company arrives at the Grey Havens where the White Ship awaits to carry the Ring-bearers beyond the circles of the world. Gandalf, Galadriel, and Elrond prepare to leave Middle-earth forever, marking the true end of the Third Age. Frodo Baggins bids a tearful goodbye to Merry and Pippin before turning to Samwise Gamgee for a final, heartbreaking parting on the quay. As the ship slips away into the West, the grey rain-curtain turns to silver glass, revealing the white shores of the Undying Lands to Frodo''s sight.' WHERE distance = 3784 * 1.60934;

-- Goal: Camp at the feet of the Tower Hills (Distance: 3814)
UPDATE goals SET description = 'Sam, Merry, and Pippin turn from the grey waters and the memory of the white ship to ride slowly eastward. The three travellers camp for the night at the feet of the Tower Hills, resting beneath the tall white towers of Emyn Beraid that shine pale in the starlight. Though the Ring-bearer has departed, the bonds of their fellowship remain as they sit together in the quiet of the evening. The road to the Shire lies just ahead, offering the promise of home to heal their parting-sorrow.' WHERE distance = 3814 * 1.60934;

-- Goal: Reach the foot of the Hills (Distance: 3839)
UPDATE goals SET description = 'Sam, Merry, and Pippin rode away from the Grey Havens in silence, the sound of the sea fading behind them as they turned their faces towards the Shire. The three companions travelled eastwards, putting the tall White Towers and the memory of the ship behind them. As they crossed the countryside, the terrain began to rise to meet the barrier of the Far Downs. They halted at the foot of these green hills, knowing that once they crested the ridge, the familiar sights of their own country would lie spread before them.' WHERE distance = 3839 * 1.60934;

-- Goal: Ahead to the east, see the crest of the Far Downs (Distance: 3864)
UPDATE goals SET description = 'Upon turning away from the Grey Havens, the three remaining companions rode slowly eastward, speaking no words but finding deep comfort in their shared presence. Sam, Merry, and Pippin traveled the long grey road together, carrying the heavy memory of the white ship''s departure. Ahead to the east, the crest of the Far Downs finally breaks the horizon, marking the western border of the Shire. This familiar sight signals that while the age of the Elves has ended, the simple life of the hobbits endures within the protection of these green hills.' WHERE distance = 3864 * 1.60934;

-- Goal: Reach the steep western face of the Far Downs (Distance: 3884)
UPDATE goals SET description = 'Sam, Merry, and Pippin turn their backs on the grey sea and the white ship, riding eastwards in a silence deep with memory. As the light failed, the steep western face of the Far Downs loomed up against the darkening sky, shielding the Shire from the salt winds of the coast. This high barrier marked the edge of the world they had known for a time, now left behind for the Ring-bearers who had passed beyond the sea. The three travellers urged their ponies up the rising ground, knowing that beyond this last great ridge lay the familiar comforts of the land they had fought to save.' WHERE distance = 3884 * 1.60934;

-- Goal: Camp next to the road (Distance: 3904)
UPDATE goals SET description = 'The three remaining travellers turn their ponies away from the grey sea and the Havens, riding slowly back towards the burgeoning life of the Shire. Words seem unnecessary as they navigate the long road, for the bond forged in peril speaks clearly enough in the silence of their journey. They halt to camp beside the road as twilight deepens, resting beneath the stars that now look down on a world changed forever. While the sorrow of parting lingers in Sam''s heart, the road ahead signifies the final return to the simple, growing things he loves.' WHERE distance = 3904 * 1.60934;

-- Goal: Begin to see grazing lands (Distance: 3919)
UPDATE goals SET description = 'Having watched the white ship disappear into the mist, Samwise Gamgee, Merry, and Pippin turn their backs on the sea and ride slowly eastward in companionable silence. The lonely road from the Grey Havens stretches out before the three hobbits, winding through the quiet emptiness of the Tower Hills. As they draw nearer to the borders of the Westfarthing, the wilder coastal heather gradually gives way to ordered fields and grazing lands familiar to their eyes. Here, the ordinary world of the Shire begins to assert itself once more, offering a quiet welcome to the weary travellers returning from the edges of the world.' WHERE distance = 3919 * 1.60934;

-- Goal: Reach Michel Delving (Distance: 3934)
UPDATE goals SET description = 'Sam, Merry, and Pippin turn their ponies from the Grey Havens and ride eastward, leaving the sound of the Sea behind them as they cross the White Downs. They arrive at Michel Delving, the chief township of the Shire, where the Mathom-house keeps its curious treasures and the Mayor presides over a land at peace. The sight of its familiar, round-windowed buildings offers a profound comfort to the travellers, grounding them once more in the simple, enduring life of their people. Here, amidst the unhurried bustle of the Westfarthing, Samwise begins to feel the true pull of his return, drawing him steadily towards his own fireside.' WHERE distance = 3934 * 1.60934;

-- Goal: Come to Waymeet (Distance: 3969)
UPDATE goals SET description = 'Sam, Merry, and Pippin turn away from the Grey Havens and ride slowly homewards, speaking no word to one another yet finding deep comfort in their shared presence on the long, grey road. The three companions traverse the familiar track through the Westfarthing, passing from Michel Delving towards the crossroads of Waymeet, where the ordinary life of the Shire flows around them once more. Although their hearts are heavy with the sorrow of parting from Frodo, the simple, enduring beauty of their homeland begins to welcome the travellers back. It is here on the Great East Road that the final leg of their broad journey draws to a close, leading them ever nearer to the firesides they fought so hard to protect.' WHERE distance = 3969 * 1.60934;

-- Goal: Sam arrives at Bag End at sunset: Home (Distance: 3991)
UPDATE goals SET description = 'Samwise Gamgee climbs the Hill as the evening light fades, finding the round windows of Bag End aglow with welcome. He steps across the threshold to Rosie and takes his daughter Elanor upon his lap, the silence of the house filled only by the crackle of the fire. The long journey to the Grey Havens is done, and the Ring-bearer has departed, leaving Sam to tend the Shire. He sits in his own chair, surrounded by the warmth of his family and the familiar sights of home. The great adventure concludes not with a battle, but with the weary traveller stating simply that he is back.' WHERE distance = 3991 * 1.60934;