-- Migration number: 0022 	 2026-01-20T00:00:00.000Z

-- Insert intermediary goals to break up large gaps (>70km) identified in goals-gaps-analysis.md
-- All distances are converted from miles to kilometers using the standard multiplier 1.60934

INSERT INTO goals (distance, title, description, special, image_id) VALUES
-- Gap #1
(435 * 1.60934, 'Camp under Glorfindel''s Watch', 'Bone-weary and stumbling, you finally halt for a precious few hours of rest, though the fear of the Black Riders presses against your mind like a physical weight. Yet here, a bright spirit burns against the unseen shadow; Glorfindel sits silent and watchful, his presence a shining barrier against the encroaching dark. Under the Elf-lord''s unblinking vigilance, you close your eyes, finding a fragile peace in the eye of the storm before the final desperate race to the Ford begins.', NULL, NULL),
-- Gap #2
(883.5 * 1.60934, 'Camp in the Naith of Lórien', 'The travelers crossed the swift Silverlode and now rest upon the cool, soft grass of the Naith, the Gore of Lórien, where no undergrowth mars the forest floor. Great grey boles of mallorn-trees rise like pillars into a canopy of pale gold, trapping a light that feels ancient and retained from a time long past. The air weighs heavy with the memory of an Elder Day, preserving a peace deeper than the earth itself. Beneath these yellow leaves, the Company sleeps within a waking dream, distinct and clear, as if the troubled world beyond the rivers has faded into shadow.', NULL, NULL),
-- Gap #3
(1555 * 1.60934, 'Camp under the holm-oaks in Ithilien', 'The travelers creep southward through the fair woodlands of Ithilien, where the air remains sweet with the scent of resin and herbs despite the gathering gloom. They seek shelter beneath the twisting branches of dark holm-oaks, their glossy evergreen leaves offering a fragile concealment from the shadow spreading out from the Mountains of Shadow. Here, amidst the lingering beauty of the garden of Gondor, they rest briefly before the final, perilous approach to the Cross-roads.', NULL, NULL),
-- Gap #4
(1675 * 1.60934, 'Camp within sight of the fortress of Durthang', 'Clad in stifling Orc-gear that reeks of the enemy, the two small travelers shrink into a cleft of rock, terrified to move under the watching eyes of the mountains. High above the road, the fortress of Durthang looms against the jagged wall of the Ephel Dúath, its iron-barred windows burning with deep, cruel red lights. All around them, the vast, arid darkness of Mordor seems to hold its breath, waiting to crush the tiny intruders who dare to creep so close to its strongholds. They crouch in the dust, overshadowed by the grim castle above and the iron jaws of the Isenmouthe below, praying to remain unseen in a land that offers no mercy.', NULL, NULL),
-- Gap #5
(1717 * 1.60934, 'Frodo and Sam cast away their orc-gear', 'The stifling weight of the heavy Orc-mail became a torment they could no longer endure, every step a battle against the crushing burden of the iron rings. With the grim clarity that they would never make a return journey needing disguise, Frodo and Sam stripped off the hateful gear and cast it into a jagged cleft. The sudden lightness brought a desperate physical relief to their trembling limbs, though it left them terrifyingly exposed to the lidless Eye. They stood stripped of all defense, small and fragile in the vast desolation, resolving to face the final ascent with nothing but their own failing strength.', NULL, NULL),
-- Gap #6
(1924 * 1.60934, 'Camp in the green lands of Anórien', 'The green fields of Anórien stretched before the returning host, traversed not in the desperate haste of war, but in the slow dignity of a funeral train. Upon the wain lay King Théoden, and though the hearts of Aragorn, Arwen, and the Fellowship were light with the peace of the West, their joy was tempered by the solemn burden they bore. The fair folk of Lórien rode beside them, their clear voices hushed in reverence as they passed through the sunlit lands. In the sweet-smelling grass they pitched their pavilions, resting in a silence that was both noble and profound.', NULL, NULL),
-- Gap #7
(1975 * 1.60934, 'Pass the beacon hill of Eilenach', 'The great wain bearing King Théoden rolls slowly past the dark, sharp peak of Eilenach, highest of the warning-beacons that once flamed against the night. Now the summit stands cold and silent above the Drúadan Forest, for the Shadow has passed and no urgent fire is needed to summon aid to Gondor. The ancient woods are hushed in reverence as the Company and the Riders of Rohan escort the golden king on his final journey, moving at a ceremonial pace through a land at peace.', NULL, NULL),
-- Gap #8
(2025 * 1.60934, 'Pass the beacon hill of Erelas', 'The Great West Road stretches out beneath the wheels of the funeral wain, a steady, rhythmic creaking that marks the slow passage through Anórien. Ahead rises Erelas, distinct among the beacon hills for its smooth, green slopes, unclad by the forests that drape its neighbors. No warning fire burns upon its summit now, only the soft light of a peaceful afternoon resting upon the treeless turf. As the company winds past, the deep silence of the land feels like a quiet reverence for the king they escort home.', NULL, NULL),
-- Gap #9
(2124 * 1.60934, 'Pass the beacon of Halifirien and the Firien Wood', 'The company climbs the rising road into the gloom of the Firien Wood, where the scent of pine resin hangs heavy and the trees stand like silent sentinels. Above the dark canopy looms the sheer, towering peak of Halifirien, the tallest of the beacons and the holy guardian of the border. Here, they pass from the stewardship of Gondor back into the realm of the Mark, guiding the King’s wain slowly through the deep, hushed shadows of the ancient forest.', NULL, NULL),
-- Gap #10
(2230 * 1.60934, 'Camp in the King''s Lands', 'The funeral procession of King Théoden moves slowly across the fertile green plains of the Folde, the personal lands of the Kings of the Mark. Borne upon a golden wain, the fallen King is escorted home with solemn honor by Éomer, Aragorn, and the Fellowship of the Ring. The shadow of war has lifted from these fields, leaving a peaceful silence as the company camps within sight of the White Mountains, preparing to return their lord to the barrows of Edoras.', NULL, NULL),
-- Gap #11
(2295 * 1.60934, 'Camp in the Westfold', 'You ride from Edoras across the fair green fields of the Westfold, journeying in state with the King of Gondor and the Lords of the Golden Wood. The land lies peaceful under the shadow of the White Mountains, healing at last from the scars of war. At a gentle pace the company camps in the dales, where talk turns eagerly to the wonders of the Glittering Caves that await at Helm''s Deep.', NULL, NULL),
-- Gap #12
(2410 * 1.60934, 'Halt at the Fords of Isen', 'The company rides from Helm''s Deep to the Fords of Isen, where the river flows past the green burial mound of Prince Théodred. Here, they halt in solemn silence to honor the King''s son who fell defending the crossing. Amidst the quiet rush of water, the riders pay their respects to the fallen before turning their gaze toward the road to Isengard.', NULL, NULL),
-- Gap #13
(2455 * 1.60934, 'Cross the River Isen', 'Leaving the Treegarth of Orthanc, the company rides south along the banks of the River Isen. At the Fords, they splash through the swift currents, crossing from the wizard''s vale into the open breeze of the Gap of Rohan. King Elessar rides at the head of the company for the last time, guiding his friends toward the parting of the ways where he must turn back to his own realm.', NULL, NULL),
-- Gap #14
(2651 * 1.60934, 'Camp among the wide grassy swells', 'The company halts amidst the vast, rolling emptiness of Enedwaith, where wide grassy swells stretch endlessly like a silent sea. As the sun sets, the misty peaks of the mountains have faded into the southern horizon, leaving the travelers alone beneath a canopy of waking stars. Here in the quiet of the wild lands, Elves, Hobbits, and the White Council rest together, finding peace in the solitude before their paths must eventually divide.', NULL, NULL),
-- Gap #15
(2696 * 1.60934, 'Pass the ruins of an ancient causeway', 'You ride along the faded spine of the ancient Royal Road, where a broken causeway rises above the wild, encroaching lands of Enedwaith. Once a proud artery of the Northern Kingdom, it is now but a grassy memory of stone, worn smooth by the relentless march of ages. The silence of the empty lands surrounds you, and the crumbled masonry speaks melancholically of the lost glory of Arnor.', NULL, NULL),
-- Gap #16
(2784 * 1.60934, 'Camp in the quiet land of Hollin', 'The Company camps amidst the ancient stones of Eregion, where the land itself seems to hold a silent memory of the Elves who once dwelt there. Galadriel and Celeborn walk beneath the dark holly trees, listening to the murmurs of the earth that lament the Noldor''s passing long ago. Though now empty of folk, the air in Hollin remains wholesome and fair, heavy with the deep, quiet nostalgia of an age that has faded into legend.', NULL, NULL),
-- Gap #17
(2934 * 1.60934, 'The Mountains of Moria loom ahead', 'The mighty peaks of Caradhras, Celebdil, and Fanuidhol pierce the sky, their white heads shining cold and remote. To Gandalf and the Hobbits, these mountains are more than stone; they stand as grim reminders of the cruel Redhorn snows and the darkness of Khazad-dûm. Beautiful yet ominous, the silent giants loom over Eregion, heavy with the memory of the struggle and loss endured beneath their roots.', NULL, NULL),
-- Gap #18
(2987 * 1.60934, 'Camp in the shadow of the Three Peaks', 'You make camp in the deep shadow of the Misty Mountains, directly beneath the three great peaks: Caradhras, Celebdil, and Fanuidhol. The sheer walls of rock cut off the sun early, casting a cold twilight over the land while the sky above remains bright. Though the air is chill with the memory of the cruel mountain spirit, the company rests safely in the quiet of these high lands, mere specks against the ancient stone.', NULL, NULL),
-- Gap #19
(3588 * 1.60934, 'Travel through the Green Hill Country', 'Frodo rode slowly through the winding lanes of the Green Hill Country, where the late afternoon sun slanted through golden leaves. The familiar beauty of the Shire ached in his heart, for he knew he was passing this way for the last time. It was a quiet, bittersweet progress, retracing old steps not in flight, but in final departure. Ahead, the road led to the Woody End, where the White Ship''s company awaited.', NULL, NULL);
